<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>The Macabre Ironies of “Trap”</h1>
    <h1>“Trap”里的恐怖与讽刺</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>Lurking beneath M. Night Shyamalan’s new thriller are the commonplace horrors of family life.</h5>
    <h5>在M. 夜. 希亚马兰的新惊悚片之下，是家庭生活中的俗套恐怖。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Some movies dispense symbols subtly, like crumbs on a backwoods trail, but in M. Night Shyamalan’s latest thriller, “Trap,” there’s one symbolic idea, and it’s unleashed with the subtlety of a thunderclap, reverberating throughout the film with relentless intensity but scant variety. I doubt whether the idea is one that Shyamalan would admit to, or whether he even intended it. Nonetheless, it’s what gives this movie more of a kick than does any manifest aspect of its tightly assembled and essentially inhuman plot: family life is murder.</p>
    <p>有些电影运用象征手法时相当含蓄，就像在荒僻的小径上洒下的碎屑，但在 M. 夜. 希亚马兰的最新惊悚片《诱捕》中，有一个象征性的概念，它以迅雷不及掩耳之势释放出来，在整部电影中以毫不留情的强度反复出现，但变化不多。我怀疑这个想法是不是希亚马兰会承认的想法，甚至怀疑他是否有意为之。尽管如此，正是这一点让这部电影比那些紧凑编排、本质上没有人情味的情节更有看点：家庭生活就是一场谋杀。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The title of the film is, in one sense, bluntly literal. Cooper Adams (Josh Hartnett), a firefighter from a suburb of Philadelphia, is taking his daughter, Riley (Ariel Donoghue), to a pop concert at a local arena. It’s soon revealed that Cooper is holding a young man captive in a basement; that the arena is swarming with police and surrounded by a SWAT team led by an F.B.I. profiler, Josephine Grant (Hayley Mills—fittingly, the star of the original “The Parent Trap”); and that the target of this intensive manhunt is a serial killer known as the Butcher. The man they’re after is identifiable not by name or face but by tiny details that the police must be on the lookout for—and he is, of course, none other than Cooper himself. The action involves Cooper’s efforts to give Riley a regular sentimental father-daughter outing while also eluding capture. It’s a story of double evasion: he must take surreptitious measures to throw law enforcement off his trail, and he must do so in a way that doesn’t break the façade of ordinariness that he sustains for Riley’s benefit.</p>
    <p>从某种意义上说，这部电影的片名相当直白。库珀·亚当斯（Cooper Adams，乔什·哈奈特饰）是一名来自费城郊区的消防员，他正带着女儿莱利（Riley，阿瑞尔·唐诺休饰）去当地体育馆参加一场流行音乐会。很快便揭露了库珀将一名年轻男子囚禁在地下室的事实；体育馆里到处都是警察，并被一支由联邦调查局剖析专家约瑟芬·格兰特（Josephine Grant，海莉·米尔斯饰——恰如其分的是，她也是原版《儿女一箩筐》的主演）带领的特警队包围；而这场大规模搜捕的目标是一位名为“屠夫”的连环杀手。他们要找的人不是通过姓名或面孔来辨认的，而是通过警方必须留意的一些细微之处——而这个人正是库珀本人。故事涉及库珀既要让莱利拥有一个普通的父女情感体验，同时又要设法躲避追捕。这是一个双重逃避的故事：他必须采取秘密措施使警方无法追踪到他的行踪，而且他还必须以一种不会破坏为莱利维持的正常表象的方式来做到这一点。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The apparent normalcy of Cooper’s relationship with Riley is conveyed through embarrassment and inadequacy—his desperately flailing effort to be a cool dad. He tries to speak the lingo, saying “jelly” for “jealous,” and, when asking her the slang meaning of “crispy,” tries dorkily to improve on it. Riley is a good student (the outing is a reward for her grades), but she’s being ostracized by other girls, which has led to tensions between Cooper and some other parents. Though Cooper seems delighted to be spending quality time with Riley, it’s obvious that the music of the concert’s headliner, Lady Raven (Saleka Shyamalan, one of the director’s daughters, who wrote several songs for her character to sing), isn’t exactly to his taste. As the concert progresses, Cooper’s increasingly bold and risky evasive maneuvers force him to dash off frequently from his seat, which suggests his aversion to attending the concert at all.</p>
    <p>库珀和瑞利之间关系的表面正常是通过尴尬和不自在传达出来的——他拼命地想要当一个酷老爸。 他试图使用年轻人的行话，用“jelly”来代替“jealous”，在向瑞利询问“crispy”在年轻人中的意思时，又笨拙地想要改进说法。 瑞利是一个好学生（外出游玩是对她成绩的奖励），但她被其他女孩排斥，这导致了库珀和其他一些家长之间的紧张关系。 虽然库珀似乎很高兴能和瑞利共度这段美好时光，但很明显，音乐会主角雷文女士（Lady Raven，由导演的女儿萨莱卡·沙马兰［Saleka Shyamalan］饰演，为自己的角色创作了几首歌曲）的音乐并不是他的菜。 随着音乐会的进行，库珀越来越大胆和冒险的闪避举动迫使他频繁地从座位上冲出去，这表明他根本不想来参加这场音乐会。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The whole story of “Trap” is on Wikipedia, for those who want spoilers. The general essence of it is the double life of Cooper Adams: his all-consuming effort to live a cheerful, ordinary life—as a father and husband with a constructive career and an admired place in the community—while also committing heinous and gruesome acts. A sense of his macabre bloodlust comes when an arena employee named Jamie (Jonathan Langdon) unwittingly tips Cooper off to the sting operation and refers to one the Butcher’s victims as having been “deli-prepped.” Cooper maintains a series of houses—in addition to (yes) the Adams-family house—in which he carries out his gory schemes. He could as easily be a bigamist, even the father of alternate families, except for what actually goes on in those houses. At home, he is a frustrated geek of unimpeachable virtue, but, in this hidden realm, he becomes the Butcher, a painstakingly constructed secret self that is his truest identity, or the one that he needs most ferociously. (There’s a fascinating tell midway through the film, a nervy lie on Riley’s behalf that he’d never have uttered were it not part of his escape plan.) Cooper enacts, as the Butcher, more than simply murder—his crimes involve intricate ruses and elaborate expertise, turning his banal life into a thrilling, high-risk adventure.</p>
    <p>“陷阱”的整个故事在维基百科上都有，对于想要剧透的人来说。其大致精髓在于库珀·亚当斯的双重生活：他一面不遗余力地过着快乐、平凡的生活——作为一个父亲和丈夫，有着积极的职业生涯和受人尊敬的社会地位，一面又犯下骇人听闻的罪行。当他得知一名名为杰米（乔纳森·朗登饰）的竞技场工作人员无意中向库珀透露了诱捕行动，并将其中一个受害者称为“熟食店准备好的”时，他的那种病态嗜血感便油然而生。除了（没错）亚当斯家的房子之外，他还拥有一系列房子，在这些房子里，他实施了一系列血腥的计划。如果不是因为那些房子里实际上发生的事情，他可能很容易成为重婚者，甚至是另一个家庭的父亲。在家里，他是一个无可挑剔的好人，但在这个隐秘的世界里，他变成了屠夫，一个精心构建的秘密自我，这是他最真实的自我，或者说是他最需要的自我。（电影中途有一个引人入胜的情节，莱利出于本能撒了一个谎，如果不是为了逃脱计划，他是绝不会说出来的。）作为屠夫，库珀所做的事情不仅仅是杀人——他的犯罪涉及复杂的诡计和高超的专业知识，将他平淡无奇的生活变成了一场刺激而高风险的冒险。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Since most criminals seek to avoid arrest, most crime stories are ones of deception, false identities, double lives. This is, of course, central to the most illustrious of all serial-killer movies, Alfred Hitchcock’s “Psycho,” which Shyamalan grafts onto “Trap” by way of Grant’s profile of the Butcher, in which she diagnoses a pathological relationship with his mother. Sure enough, Cooper intermittently hallucinates an elderly woman and her voice. It’s an effortful bit of psychologizing, plainly cooked up just to squeeze in a nod to Norman Bates’s motivating pathology, but, more significant, it’s also a red herring, albeit one that Shyamalan likely didn’t even intend to create. Positing a mother complex as Cooper’s motivation shifts viewers’ attention from one that’s hiding in plain sight: the commonplace horrors of a mundane family life. (If you think Riley’s been picked on before, wait till the other kids find out that her father’s a serial killer.)</p>
    <p>由于大多数罪犯都试图逃避逮捕，所以大多数犯罪故事都是欺骗、假身份、过双重生活的故事。这当然是所有连环杀手电影中最负盛名的阿尔弗雷德·希区柯克(Alfred Hitchcock)的《惊魂记》(“Psycho”)的核心，而奈特·沙马兰通过格兰特对屠夫的描述，将《惊魂记》移植到了《陷阱》中，在这段描述里，她诊断出他与母亲的关系病态。果然，库珀间歇性地产生一位老妇人及其声音的幻觉。这是一种用力过猛的心理描绘，显然是为了向诺曼·贝茨(Norman Bates)的动机病理致敬，但更重要的是，这也是一种误导，尽管沙马兰可能无意为之。把恋母情结设定为库珀的动机，转移了观众的注意力，使他们忽略了隐藏在光天化日之下的东西：平凡家庭生活中司空见惯的恐怖。（如果你觉得莱利以前被欺负过，那就等着瞧吧，等其他孩子知道她父亲是个连环杀手的时候。）</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>“Trap” is a movie of two kinds of action. Shyamalan realizes one of them expertly: the action of the eye. The story is centered on gazes—on Cooper’s quick perception of chances to take, escape routes to exploit—and the director captures these sight lines with virtuosic relish. The arena’s spaces almost become characters in themselves, and the large part of the movie that’s set there is an inspired windup toy of mechanical possibilities.</p>
    <p>「圈套」是一部包含两种动作的电影。 shyamalan 对其中一种处理得尤为出色：目光的动作。故事围绕着眼光展开——围绕着库珀迅速察觉可趁之机和可利用的逃生路线——而导演则以大师级的热情捕捉到了这些视线。片中的场域空间几乎成为了角色本身，而设于其中的大部分剧情则像是一个充满灵感的机械玩具，蕴藏着各种可能性。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>But, as cinematic gazes go, the ones in “Trap” are also ones without subjectivity. Even when they present, unambiguously, a character’s point of view, they don’t conjure an inner life—the object of the gaze dominates the subject, in part, because those objects are instantly reduced to their function in the plot, whether in Cooper’s machinations or in other characters’ pursuit of him. “Trap” offers little sense of larger-scale observation, of scanning, of the wide spaces in which Cooper operates, and amid which he zeroes in on the salient possibilities for escape. The film presents the immediate effects of Cooper’s arachnid scheming but rarely conveys the feeling that he’s thinking at all. For as long as the drama stays in the arena, the venue becomes effectively the protagonist and gives the movie energy. When the action eventually propels Cooper outside the confines, that energy dissipates.</p>
    <p>但就电影中的目光而言 《陷阱》里的目光是缺乏主体性的 即便它们毫不含糊地 呈现出角色的视角 也无法让人感受到其内在生命—— 被注视的对象在某种程度上 控制了注视的主体 这是因为这些对象很快就被简化为 故事发展中某个功能性的存在 不论是在库珀的计谋中 还是在其他角色对他的追逐里 《陷阱》几乎没有展现出 更广阔视域中的观察 没有展现出 库珀所处的广阔空间 以及他如何从中锁定 逃脱的可能性 电影展现的是 库珀如蜘蛛般布局的直接后果 却很少让人感觉到 他在思考 当剧情还在斗牛场内展开时 斗牛场本身就成了 实质上的主角 并赋予了电影活力 而当故事最终将库珀 推向场外 那份活力也随之消散</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>To give the tightly mechanical plot a semblance of life, Shyamalan fills it out with piquant details: there’s Cooper’s pally rapport with the attendant Jamie (which enables him to steal the guy’s employee badge, and then use it to steal another employee’s documents and snag a police walkie-talkie); there are awkward chance encounters with the mother (Marnie McPhail) of an ex-friend of Riley’s. The backstage world of Lady Raven’s show affords more of this: another musician (Kid Cudi) throws hissy fits over his snacks, a concert-tour employee (Vanessa Smythe) reveals details of stage management, and there are notable protocols and practices involving law-enforcement officers. What all these bits of local color have in common is that they show ordinary people as dupes, and Shyamalan, in depicting a world deceived by Cooper’s pretenses, also reveals one deceived by its own self-importance. Like Cooper, Shyamalan confidently sees through the vanity. His vision is a sardonic one, and it feels as if his cinematic smirks conceal rage at the impotence and banality of which ordinary life is made. The film’s ironies aren’t cosmic—they’re the tantrum of an inhibited man who only cautiously reveals a lurking sympathy for the Devil.</p>
    <p>为了给这个严密而机械的情节增添一丝生机，沙马兰用生动的细节填充了它：库珀和管理员杰米之间轻松随意的互动（这让他得以偷走后者的员工证，进而再用这张证件去偷另一位工作人员的文件，并顺走一部警用手持对讲机）；瑞利前友人的母亲（玛妮·麦克菲饰演）和他几次尴尬的偶遇。拉文女士演出的后台提供了更多这样的细节：另一位音乐人（说唱歌手卡迪小子饰演）因为自己的小吃而闹脾气；巡演工作人员（瓦内萨·斯迈思饰演）透露了一些舞台管理方面的细节；还有一些涉及执法人员的特定规程和做法。所有这些充满地方色彩的细节有一个共同点，那就是它们把普通人描绘成了容易受骗的人。在展现一个被库珀的伪装所欺骗的世界的同时，沙马兰也揭示了一个被自我重要性所蒙蔽的世界。和库珀一样，沙马兰自信地看穿了这种虚荣。他的视角是愤世嫉俗的，感觉他在电影中的冷笑掩饰着对于普通生活无力感和平庸本质的愤怒。这部电影中的讽刺意味并不是宇宙级的——它们更像是一个受压抑之人的发泄，他只是谨慎地流露出对恶魔隐隐的同情。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>