<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>The Supreme Court Needs Fixing, but How?</h1>
    <h1>最高法院需要修补，但如何修？</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>President Biden has proposed radical changes to the Court. Reviewing them is a reminder of why reform is so hard, despite dissatisfaction and a wealth of ideas.</h5>
    <h5>拜登总统提议对法院进行激进改革。回顾这些提议就让人想到，尽管大家都不满而且各种想法层出不穷，改革却依然举步维艰。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Politics, more than many fields, can be unjust. Last week, at the L.B.J. Presidential Library, in Austin, President Joe Biden boasted about his judicial expertise: “I’ve been told that I’ve overseen more Supreme Court nominations as senator, Vice-President, and President than anyone in history—anyone alive today, I should say.” As chairman or ranking member of the Senate Judiciary Committee, Biden did help manage the confirmation hearings of eight nominees to the Court (one of whom, Robert Bork, was voted down) and a Chief Justice. That’s almost a full bench. But as President he has named only one Justice: Ketanji Brown Jackson. Donald Trump, on the other hand, whose most intense court experiences before going to the White House were with bankruptcy judges, put three Justices on the Court—Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett.</p>
    <p>政治比许多其他领域更可能遭遇不公。上周，在位于奥斯汀的林登·贝恩斯·约翰逊总统图书馆，乔·拜登总统自夸起了自己的司法专长：“有人告诉我，作为参议员、副总统和总统，我经手的大法官提名人数超过在世的所有人。”在担任参议院司法委员会主席或首席委员期间，拜登确实参与主持了八位大法官（其中一位，罗伯特·博克，未获通过）及一位首席大法官的确认听证会。这几乎相当于一整个大法官团队了。但作为总统，他目前只提名了一位大法官：凯坦吉·布朗·杰克逊。而唐纳德·特朗普在入主白宫前最深刻的法庭经历无非是破产法庭，却成功让尼尔·戈萨奇、布雷特·卡瓦诺和艾米·科尼·巴雷特三位大法官上任。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Now, two years after those three helped to overrule Roe v. Wade, there is a sense that something is off balance about the Court—about its composition, its ethics, and its general connection to democracy. Its approval ratings hover around thirty-five per cent. And it was clear, in Austin, that Biden himself felt cheated. Trump didn’t benefit just from fate; Mitch McConnell, then the Senate Majority Leader, had held one seat open for him in 2016 and kept another in his hands by rushing the process in 2020. The result, Biden said, was a Court marked by “extremism,” with its legitimacy at risk. He had long resisted pressure from the left flank of his party to pursue Court reform, but with only months left in the White House, he had come to offer a set of radical changes.</p>
    <p>如今，在这三人在推翻“罗伊诉韦德案”中发挥作用的两年后，人们普遍感觉最高法院在人员构成、伦理道德和与民主的一般性联系方面都出现了失衡。它的支持率徘徊在35%左右。在奥斯汀，显而易见的是，拜登本人感觉受到了不公平的对待。特朗普不仅得益于命运；当时的参议院多数党领袖米奇·麦康奈尔在2016年为他空出了一个席位，并且在2020年通过加快程序将另一个席位留在自己手中。拜登表示，结果就是最高法院打上了“极端主义”的烙印，其合法性受到威胁。他长期以来一直顶着党内左翼要求改革最高法院的压力，但在白宫任期仅剩数月之际，他提出了一系列激进的变革。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>To review Biden’s proposals, though, is to be reminded of why reforming the Court is so hard, despite the dissatisfaction and a wealth of ideas. He proposed three measures, the first of which is not so much a reform as a rebuke: the “No One Is Above the Law Amendment” to the Constitution. It would effectively overrule the Court’s decision, in Trump v. United States, dangerously asserting that former Presidents have broad immunity from criminal prosecution for their actions in office. But any amendment requires first a two-thirds majority in each house of Congress, and then ratification by three-quarters of the states—thirty-eight in all, a big number. Alternatively, two-thirds of the state legislatures could demand a constitutional convention, which might put the entire document up for grabs. This has never happened, and could be calamitous in a time of Trumpism.</p>
    <p>但回顾拜登的提议会让人想起，尽管人们普遍不满且提议众多，改革最高法院却难上加难。他提出了三项措施，其中第一项与其说是改革不如说是一种谴责：“无人可凌驾于法律之上宪法修正案”。该修正案将实质上推翻最高法院在“特朗普诉美国案”中的判决。该案危险地认为，总统在任期内的行为享有广泛的免受刑事起诉豁免权。但任何一项宪法修正案都需要国会两院三分之二多数通过，然后还需要四分之三的州（总共38个州）批准——这是一个很大的数目。或者，三分之二的州议会可以要求召开制宪会议，这可能会让整部宪法面临改写的命运。这种事情从未发生过，在特朗普主义盛行的当下，这么做可能是一场灾难。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Biden’s second proposal was for staggered term limits, with each Justice serving eighteen years, instead of the current lifetime appointment. In theory, this would give every President two picks per term. There is much to recommend term limits; the United States is an outlier in not having them. Until the late nineteen-sixties, Justices spent an average of about fifteen years on the Court; for those who have departed since 1970, the average has been about twenty-six years. A fixed term might make the confirmation process less ugly and less expensive (tens of millions are now spent on lobbying and ads), addressing problems that aren’t confined to one party. There might be more room for deliberation and less for resentment.</p>
    <p>拜登的第二个提议是交错设置任期限制，每位大法官任职 18 年，而非当前的终身任命。从理论上讲，这样每位总统每届任期内可以有两次提名机会。设置任期限制有很多好处；美国是不设任期限制的特例。直到 20 世纪 60 年代末，大法官平均在最高法院任职约 15 年；而自 1970 年以来离职的大法官，平均任职时间约为 26 年。固定任期或许可以让提名确认程序不那么丑陋，成本也没那么高（现在游说和广告要花费数千万美元），并且能解决不止一个党派面临的问题。这样或许能让审议过程有更多空间，减少怨恨情绪。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>However, a Presidential commission on the Supreme Court, convened in 2021, was divided over whether term limits would require a constitutional amendment. Under the Constitution’s Article III, federal judges “hold their Offices during good Behaviour,” which has meant for life, as long as they aren’t impeached and convicted. (No Justice has ever been removed that way.) There are a number of proposals for getting around the lifetime rule legislatively—assigning a less powerful “senior” role to longer-serving Justices, or creating “temporary” seats on the Court—but each has risks. And the Court would probably consider itself the arbiter of constitutionality.</p>
    <p>然而，总统于2021年召集的最高法院委员会在任期限制是否需要宪法修正案的问题上存在分歧。根据宪法第三条，联邦法官“在表现良好期间任职”，这意味着只要他们不被弹劾和定罪，他们就可以终身任职。(从来没有法官以这种方式被移除。)有许多提案可以在立法上绕开终身任职规则，比如将权力较小的“高级”职位分配给任职时间较长的法官，或者在最高法院设立“临时”席位，但每一项都有风险。法院可能会认为自己是合宪性的仲裁者。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Biden’s third proposal should be the most achievable: an enforceable code of ethics for the Justices, which Congress could pass. Right now, for offenses that aren’t impeachable, the only code the Justices have is voluntary. An effective code of ethics might, for example, allow the Chief Justice to mandate the recusal of a Justice owing to a conflict of interest (if, say, a spouse did work for an advocacy group) or strengthen the rules on gifts (an issue for Clarence Thomas, among others). It might, in short, make the Court seem a little less shady and a bit more legitimate. But it wouldn’t change its structure or, necessarily, alter its ideological dynamics.</p>
    <p>拜登的第三项提议应当是最容易实现的：为大法官们制定一套具有约束力的职业道德规范，这可以由国会通过立法来完成。目前，对于那些不构成弹劾条件的行为，大法官们遵循的职业道德规范完全是自愿性的。比如，一套行之有效的职业道德规范可能会授权首席大法官因利益冲突（比方说，大法官的配偶受雇于某个游说团体）而要求某位大法官回避，或者加强对馈赠行为的规定（克拉伦斯·托马斯等人都涉及这一问题）。总而言之，它可以提升最高法院的形象，减少其给人留下的暗箱操作的印象，增强其合法性。但它不会改变最高法院的架构，也不一定会改变其意识形态格局。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Yet, even an ethics code seems hard to achieve. Speaker of the House Mike Johnson called Biden’s proposals “dead on arrival.” Vice-President Kamala Harris endorsed them, and she has expressed openness to ambitious reforms in the past, but it remains to be seen if she will run on any of these ideas, or make them priorities if she wins the election. Chuck Schumer, the Senate Majority Leader, was noncommittal about Biden’s plan, even as he called the Court a “morass.” Reform may be a generational project.</p>
    <p>然而，就连制定伦理准则也似乎难以实现。众议院议长迈克·约翰逊（Mike Johnson）称拜登的提议“根本没戏”。副总统贺锦丽虽然支持这些提议，并且她过去对大胆改革持开放态度，但目前尚不清楚她是否会将上述任何想法纳入自己的竞选纲领，或者如果她赢得大选是否会将这些想法作为优先事项。参议院多数党领袖查克·舒默在评价拜登计划时含糊其辞，尽管他也称最高法院陷入了“泥沼”。改革或许是一项跨世代的工程。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>One idea that Biden stayed away from is increasing the number of Justices—or, as critics call it, packing the Court. Such a move is seen as disreputable by many, in part because of the threat of escalation. (Would Presidents add Justices each time they controlled Congress? Trump might.) Ironically, expansion could be achieved by getting a law through Congress, and so would be simpler than a lot of other measures—it’s easier to get people on the Court than off it. In 1937, when Franklin D. Roosevelt called for expanding the Court, after the Justices repeatedly blocked key New Deal legislation, the threat was not idle. A crisis was avoided after a Justice changed his position. A lesson there may be that even unrealistic proposals can encourage a reckoning.</p>
    <p>拜登避开的一个想法是增加大法官人数——或者用批评者的话来说，就是填塞法院。许多人都认为这种做法有失体面，部分原因是它可能引发报复。（总统今后是否每次控制了国会都要增加大法官？特朗普或许会这么做。）颇具讽刺意味的是，扩充大法官可以通过国会立法来实现，因此比许多其他措施更简单——让人进入法院任职总比让他们离职容易。1937年，富兰克林·德拉诺·罗斯福在最高法院多次阻止新政关键法案后呼吁扩大法院规模，这一威胁并非虚张声势。后来一位大法官改变了立场，才避免了一场危机。从中我们可以吸取的教训是：即便不切实际的提议也能促使人们进行清算。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>What’s less well remembered about F.D.R.’s plan is that it was tied to age: one seat would be added for every Justice who was seventy or older, to a maximum of fifteen. In 1937, no fewer than six Justices were at least that old; now, three of them are. Justice Thomas is seventy-six, Samuel Alito is seventy-four, and Sonia Sotomayor is seventy. The age question adds a certain poignancy to Biden’s quest for reform, in more ways than one. Not long before he dropped out of the race, he said that the next President would get to choose “a couple of Justices.” He was referring, presumably, to possible resignations from the bench and to the role of time and chance—and of elections. If Trump wins, he could have, between his two terms, five appointees, or more. If he doesn’t, a woman, for the first time, stands to do the picking. And the Court will change.</p>
    <p>人们不大记得的是，F.D.R. 的计划是与年龄挂钩的：每有一位七十岁或以上的法官，就增加一个席位，最多增加到十五个。1937 年，不少于六位法官年事已高；如今，有三位法官年事已高。托马斯法官现年七十六岁，塞缪尔·阿利托七十四岁，索尼娅·索托马约尔七十岁。从不止一个层面上讲，年龄问题给拜登寻求改革增添了某种伤感。在退选前不久，他曾表示下任总统将有机会提名“几位法官”。他所说的大概是可能辞职的法官以及时间、运气和选举的作用。如果特朗普胜选，两届任期内他将有机会提名五位法官，甚至更多。如果不是他，那么将首次由一位女性来提名法官。而最高法院也将发生变化。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>