<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>“Weird” Is a Rebuke to Republican Dominance Politics</h1>
    <h1>“ Weird ” 是对共和党主导政治的驳斥</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>The Democrats’ new favorite attack line has less to do with their opponents’ distance from the norm than with their desired level of control.</h5>
    <h5>民主党人新宠的攻击路线与其说与他们的对手偏离常规的程度有关，不如说与他们想要的控制程度有关。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Are you weird? According to Democrats—who have made “weird” a new term of art for Republicans—you’re weird if you get overexercised about the genitalia of Olympic athletes, think childless people shouldn’t have the right to vote, and generally fixate on controlling women, families, gender, and sexuality for reasons that seem transparently bound up in your own embattled masculinity and deep shame. You’re weird if you yell in public about sharks, or about “Joe Biden’s border bloodbath,” especially while your hands dance to music only you can hear. You’re weird if you want to track strangers’ menstrual cycles but are mad that people know you Googled “dolphin porn.” You’re weird if you campaign vigorously on issues that fly against common sense, such as getting rid of library books, abolishing the Department of Education, and giving the President dictatorial powers. “Weird” is multipurpose, a catchall designation for extreme or intense things that Republicans do or say. Its capaciousness is part of its appeal.</p>
    <p>你古怪吗？按照民主党人的说法——他们将“古怪”打造成了一个形容共和党人的新术语——如果你对奥运选手的生殖器过于上心，认为没有子女的人不该有投票权，总体上执着于以似乎明显与你自身饱受挑战的男子气概及深深羞耻感捆绑在一起的方式控制女性、家庭、性别和性取向，那你就是古怪。如果你在公共场合大喊大叫谈论鲨鱼，或者谈论所谓的“乔·拜登边境血案”，尤其是同时你的双手随着只有你自己能听到的音乐翩翩起舞，那你就是古怪。如果你想要追踪陌生人的月经周期，却又对自己谷歌搜索“海豚色情”的事情被人知道感到恼火，那你就是古怪。如果你在那些违背常识的问题上积极竞选，比如清除图书馆的书籍、废除教育部或赋予总统独裁权力，那你就是古怪。“古怪”这个词用途广泛，是一个用来形容共和党人极端或过激言行的万能标签。它的包罗万象正是其魅力的一部分。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>It’s only a bit of an exaggeration to say that, semantically, “weird” doesn’t really mean anything. The Democrats’ disinclination to sharpen their critique telegraphs a desire to get on with it: to speed toward the future rather than linger in 2016. Back then, the liberal line on Trump was that he was “not normal,” and that his conduct as President should not be “normalized”—a rhetorical strategy that failed because “normal” doesn’t really mean anything, either. Eight years ago, “normal” could easily be bent to accommodate the democratically elected occupant of the White House and one of the most powerful men in the world. A President has too much status, and can launch too many warheads, to be prosecuted for strangeness alone. Maybe we’re the strange ones for voting them into office?</p>
    <p>说“古怪”在语义上其实没什么意义，这么说虽有些夸张，但也不算太过分。民主党人不愿意尖锐地批评，这表明他们只想尽快向前走：加速奔向未来，而不是停留在 2016 年。当时，自由派对特朗普的论调是，他“不正常”，作为总统，他的行为不应该被“正常化”——这一修辞策略之所以失败，是因为“正常”这个词本身也毫无意义。八年前，“正常”很容易就能被拿来描述一位民选的白宫主人、世界上最强大的人物之一。总统的地位太高，能发射的核弹头太多，仅凭古怪这一点就对他们发起起诉，似乎行不通。或许我们这些投票让他们上台的人才更古怪吧？</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The reversal of that dynamic surely accounts for some of the glee that the “weird” brigadiers are spreading. My colleague Jay Caspian Kang proposes that “weird . . . allows liberals to slap back at years of similar aspersions from the right.” Socially progressive parties are more often tagged as outré, Kang observes, and so it’s satisfying to turn the tables, to “normalize [one’s] politics through the imagined average voter.” Democrats do seem relieved by a mounting conviction (among other Democrats, at least) that Republicans are not just cruel but deviant, and they have plenty of evidence to draw on, in the form of outlandish policy proposals and absurd comments. But another redefinition also appears to be taking place. The way liberals are using it, “weird” has less to do with one’s distance from the norm than with one’s desired level of control. With the Weird Sisters, in “Macbeth,” Shakespeare evoked the Fates, classical beings who decided who was born, exactly how long they lived, and how they died. The liberal capture of “weird” subtly registers that older valence, antiquity’s spin on the “control freak.”</p>
    <p>这种动态的逆转肯定能解释“怪咖”派的部分洋洋自得。我的同事杰·卡斯珀恩·康（Jay Caspian Kang）提出，“怪咖……让自由派得以反击多年来来自右翼的类似恶意攻击。”康观察到，社会进步党派更常被打上异类的标签，因此把这种标签转贴给对方、向“想象中的普通选民”证明自己政治立场的正当性是一件大快人心的事。民主党人似乎确信共和党不仅残忍而且变态，这让他们如释重负；而且他们也有大量证据可举，比如离谱的政策提案和荒谬的言论。但另一个新的定义似乎也在形成。“怪咖”在自由派口中的含义与其说是与常规的距离，不如说是一种想要控制一切的愿望。在《麦克白》中，莎士比亚描写女巫时借鉴了命运三女神的形象——这些古典神话人物决定着人的出生、寿命及其死亡的方式。自由派对“怪咖”的重新定义巧妙地呼应了这一古老含义——就像古时候的“控制狂”。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>When “they go low, we go ‘ew,’ ” Monica Hesse wrote in a smart piece praising “weird” ’s efficacy as a tactic. Hesse focussed on the word’s air of schoolyard contempt, which, she argued, reframed the would-be bad boys of the right as “kids in the corner eating glue off their hands.” But though “weird” is snarky, it’s not an epithet that would gladden bullies’ hearts. It’s not vindictive; it’s not precise. It doesn’t belabor the point, perhaps because displaying such antipathy and rancor toward another person would be, well, weird. Instead, “weird” is dismissive, implying that the specifics aren’t worth getting into: the brisk impatience of a tweet from Representative Alexandria Ocasio-Cortez, when she had to explain the phenomenon to Vivek Ramaswamy, is a far cry from the sadism we’ve come to expect from Trumpworld. (“Trying to watch what LGBTQ+ people do all the time is abnormal. Punishing people who don’t have biological offspring is creepy,” Ocasio-Cortez wrote crisply, as if annoyed to have to spell it out.) There’s an implicit expectation that weird behavior is temporary, a passing fever rather than an inherent trait. This contrasts with the brutal, identity-based attacks that characterize the MAGA movement.</p>
    <p>莫妮卡·赫斯在一篇见解独到的文章中赞赏了“古怪”一词作为策略的有效性，她写道，在对方“出下策”时，我们只需说声“真倒胃口”。赫斯聚焦于这个词在学校操场上弥漫的那种鄙夷意味，并认为它重新定义了右翼那些自以为是的“坏小子”，把他们比作“坐在角落里舔手上的胶水的小孩”。尽管“古怪”一词略带嘲讽，但它还算不上能让恃强凌弱者欢欣鼓舞的骂人话。它并不充满恶意，也不够精准到位。它不会过分纠结于某个点上——或许是因为对另一个人表现出如此强烈的敌意和愤恨本身就是一件“古怪”的事。相反，“古怪”一词具有轻蔑之意，意味着没有必要深究细节：众议员亚历山大·奥卡西奥-科尔特斯在推特上解释这一现象时流露出的不耐烦与我们从特朗普世界所预料到的那种残忍大相径庭。（奥卡西奥-科尔特斯干脆利落地写道：“一直盯着同性恋群体的行为是不正常的。惩罚没有亲生子女的人很诡异。”她似乎很不耐烦，不得不将话说得这么明白。）言外之意似乎是，古怪的行为只是暂时的，就像发烧一样，很快就会过去，而不是一种固有的特征。这与MAGA运动中那些残酷的、基于身份的攻击形成了鲜明对比。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>For all the attention paid to how the word “weird” paints Republicans, its real utility seems to lie in the image it projects of Democrats. On the spectrum of insults, “weird” is fairly mild, with just enough sting to mean business—more of a forceful call-in, in contemporary parlance, than a devastating callout. The new rhetoric has helped prominent men in the Party, from Governor Tim Walz to Senator Chris Murphy to Senator Chuck Schumer, present an alternate vision of masculinity: something stoic, down-to-earth, relaxed, and trustworthy. Tellingly, Walz, who has been most closely tied to the attack, was just announced to be the Vice-Presidential nominee. Speaking about his Republican counterpart J. D. Vance, Walz, a former football coach, said, “It’s weird. I don’t want him talking about my family.” A more universal sentiment can hardly be imagined, and it’s especially charming in the mouth of America’s Midwestern Dad. In general, the “weird”-slinger comes off as frustrated but hopeful; under no illusions about his opponent but still fundamentally reasonable; prepared to indulge in some well-warranted ridicule but not to compromise his decency. These are the same old Dems, in other words, but newly willing to bring the fight. It’s no accident that “weird” ’s rise has coincided with Kamala Harris’s ascendency as a candidate, a moment of political renewal that has galvanized listless liberals. Rhetorically, “weird” conveys that unusual times call for unusual measures, and that the Democrats have finally figured out how to go both low and high at once.</p>
    <p>“诡异”这个词尽管被大加利用来形容共和党人，但其真正的用武之地似乎在于它所塑造的民主党形象。在侮辱的话语体系中，“诡异”算是比较温和的，但也足够尖锐，能表达出言者的态度——按照现在的说法，与其说这是一种毁灭性的公开抨击，不如说是一种强有力的电话连线。这种新的修辞方式帮助了州长蒂姆·沃尔兹、参议员克里斯·墨菲和参议员查克·舒默等党内知名男性展现了一种另类的男子气概：沉着冷静、脚踏实地、轻松自在且值得信赖。颇具意味的是，与这番攻击联系最为紧密的沃尔兹刚刚被宣布为副总统候选人。谈到自己的共和党对手J.D.万斯时，曾任橄榄球教练的沃尔兹表示：“真是诡异。我不想让他谈论我的家人。”很难想象还有什么比这更普遍的情绪了，这话从这位美国中西部父亲般的口中说出，格外动人。总的来说，“诡异”这个词的使用者显得既沮丧又充满希望；对对手没有丝毫幻想，但依然保持着基本的理性；准备进行一些有充分理由的嘲讽，但不会因此丧失体面。换言之，这些民主党人还是老样子，但现在他们更愿意迎战对手。“诡异”的兴起与卡玛拉·哈里斯作为候选人的崛起不谋而合，这是一个政治更新的时刻，激发了萎靡不振的自由派人士的热情。从修辞的角度来看，“诡异”传达了一个信息：非常时期需要采取非常手段，而民主党人终于学会了如何同时采取低姿态和高姿态。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>There’s even a hint of caregiving in the left’s language. Weird is the sort of word a parent might use to wave away a child’s anxiety—“A monster in the closet would be pretty weird, huh?” It’s a way of acknowledging a fear without assigning it too much power. And it’s a form of containment. There’s a sense of quarantining this baffling political weirdness away from the rest of the country, not in anything so crazy as a physical structure—no need for that—but simply in a word, a gust of air, some sound attached. The wager of “weird” is that Americans of all stripes have been longing for de-escalation, a cooling hand on their brow, and that they’ll welcome a chance to distance themselves from the perceived fringe. Biden’s Presidency may have offered a measure of stability and sanity to those reeling from the unreality of the Trump years, but his reëlection campaign did not. The country seemed to be sleepwalking toward November as Trump’s rhetoric darkened and the Democratic establishment dismissed clear evidence of their candidate’s decline. As in a nightmare, we all had rigor mortis and couldn’t open our mouths to protest when we were told that these two men represented the best our political system had to offer. Harris, when she moved to the top of the ticket, jolted many people back to life. The fear and confusion aren’t gone, but her candidacy diminishes those feelings, makes them seem silly and insignificant. By running Harris, Democrats are signalling that they refuse to dwell in denial; and, therefore, that they refuse to fight MAGA on its own fantastical turf. If she wins, the country has a shot at waking up from an extremely weird dream.</p>
    <p>甚至在左翼的措辞中都能感受到一丝抚慰。“怪异”这个词就像是父母用来安抚孩子焦虑情绪时会说的话——“衣橱里有怪物，这可真够怪异的，对吧？”这是一种承认恐惧的方式，但又不会赋予这种恐惧太多力量。这也是一种约束方式。这个词让人感觉到仿佛将这种令人困惑的政治怪诞性与美国其他地方隔离开来，并不需要什么实体结构——那样太疯狂了——只需要一个词、一口气、一点声音附着其上即可。“怪异”这个词所寄托的希望是，所有派别的美国人都渴望局势降温，希望能有一只冷静的手放在他们的额头上，他们会欢迎有机会让自己远离他们认为的边缘群体。拜登的总统任期或许为那些因特朗普执政期间种种不真实感而感到天旋地转的人提供了一定程度的稳定性和理智，但他的连任竞选却没有。随着特朗普的言辞日益阴暗，民主党高层无视其候选人衰落的明显迹象，这个国家似乎浑浑噩噩地走向11月。仿佛身处梦魇一般，当我们被告知这两个人就是我们政治体系所能提供的最佳人选时，我们都动弹不得，无法开口抗议。当哈里斯成为总统竞选搭档时，许多人都猛然惊醒。恐惧和困惑并没有消失，但她参选减少了这些感觉，让这些感觉显得愚蠢且无足轻重。提名哈里斯参选表明民主党拒绝沉溺于否认现实之中；因此，他们也拒绝在MAGA自己的幻想之地与其斗争。如果她能胜出，这个国家就有机会从一场极其怪异的梦中醒来。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>