<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>What Does It Really Mean to Learn?</h1>
    <h1>学习的真正含义是什么？</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>A leading computer scientist says it’s “educability,” not intelligence, that matters most.</h5>
    <h5>一位顶尖的电脑科学家说，重要的不是智力，而是“可教育性”(educability)。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>I read “Middlemarch” for the first time during my sophomore year of college. I didn’t get it. Why would Dorothea, a young and intelligent woman, marry that annoying old man? How could she be so stupid? No one else in the class seemed to get it, either, and this pushed our professor over the edge. “Of course you don’t understand,” he roared, swilling a Diet Coke. “Trust me, you’ll read this book again when you’re forty, after your first divorce, and you’ll say, ‘Oh, I see!’ ”</p>
    <p>我在大学二年级时第一次读《米德尔马契》，但没读懂．一个年轻且聪明的女人，为什么非要嫁给那个讨厌的老头呢？她怎么能那么傻呢？班上似乎也没人懂，这把教授给气坏了。“当然你们不懂，”他吼道，一边摇晃着手里的健怡可乐，“相信我吧，等你们四十多岁，经历了第一次离婚后再读这本书，就会恍然大悟地说：哦，原来如此！”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Arguably, it’s one of the tragedies of humanities education that so much of it occurs between the ages of eighteen and twenty-two. We don’t teach people to drive at twelve, when they’re carless; why should we make them read novels about life’s regrets when they have none? Yet there’s a theory behind the assignment of “Middlemarch” to sophomores: it’s that knowledge acquired too early gets stored away. Patterns of thinking established now will be retraced later; ideas encountered first in art will prime us for the rest of life. This sounds chancy and vague, until you reflect on the fact that knowledge almost never arrives at the moment of its application. You take a class in law school today only to argue a complicated case years later; you learn C.P.R. years before saving a drowning man; you read online about how to deter a charging bear, because you never know. In the mid-twentieth century, Toyota pioneered a methodology called just-in-time manufacturing, according to which car parts were constructed and delivered as close as possible to the hour of assembly. This was maximally efficient because it reduced waste and the cost of storage. But the human mind doesn’t work that way. Knowledge must often molder in our mental warehouses for decades until we figure out what to do with it.</p>
    <p>可以说，人文学科教育的一大悲哀之处在于，这种教育大多是在一个人十八岁到二十二岁之间进行的。我们不会在人们十二岁、还没有车的时候教他们开车；为什么要在他们对人生毫无悔意的时候，让他们去读那些描写人生遗憾的小说呢？不过，让大二学生读《米德尔马契》自有其理论依据：那就是过早获取的知识会被储存起来。现在形成的思想模式以后还会再现；而首次从艺术中接触到的理念会为今后的人生打下基础。这听起来有些冒险且模糊不清，但你转念一想就会发现，知识几乎从来不会在其应用的一刻才到来。你今天在法学院上课，几年后才会接手复杂的案件；你在多年前学会了心肺复苏术，却在多年后才用它救了一名溺水者；你在网上阅读如何吓退一头向你冲来的熊的文章，因为你永远不知道自己什么时候会遇到这种情况。二十世纪中期，丰田开创了一种名为“及时生产”的管理方法，根据这种方法，汽车零件会在组装前尽可能短的时间内制造并运送到厂。这样做效率最高，因为这样可以减少浪费和存储成本。但人的大脑并不是这样工作的。知识往往要在我们的思维仓库中尘封数十年，直到我们知道该如何使用它们。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Leslie Valiant, an eminent computer scientist who teaches at Harvard, sees this as a strength. He calls our ability to learn over the long term “educability,” and in his new book, “The Importance of Being Educable,” he argues that it’s key to our success. When we think about what makes our minds special, we tend to focus on intelligence. But if we want to grasp reality in all its complexity, Valiant writes, then “cleverness is not enough.” We need to build capacious and flexible theories about the world—theories that will serve us in new, unanticipated, and strange circumstances—and we do that by gathering diverse kinds of knowledge, often in a slow, additive, serendipitous way, and knitting them together. Through this process, we acquire systems of beliefs that are broader and richer than the ones we can create through direct personal experience. This is how, after our first divorce, we find that we can draw on wisdom borrowed from English literature.</p>
    <p>哈佛大学教授、著名计算机科学家莱斯利•瓦利安(Leslie Valiant)认为，这其实是一种优势。他将人类长期学习的能力称为“可教育性”(educability)，并在新书《可教育性的重要性》(The Importance of Being Educable)中提出，这种能力是我们取得成功的关键。当我们思考是什么造就了人类大脑的与众不同，往往会把关注点放在智力上。但瓦利安写道，如果我们要想把握现实世界的复杂性，“仅仅聪明是不够的”。我们需要构建出关于这个世界的容量大且灵活多变的理论——这些理论能帮助我们在全新的、不可预见的和奇怪的情况下应对自如——而我们通过收集各种各样的知识（往往以缓慢、累加、偶然的方式），再将它们编织在一起，就能形成这样的理论。通过这一过程，我们获得的信仰体系比仅凭个人直接经验所能创造的更为宽泛、更为丰富。因此，在经历第一次离婚后，我们会发现自己可以借鉴从英国文学中学到的智慧。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Valiant won the 2010 Turing Award, his discipline’s version of the Nobel Prize, for developing ideas that underpin artificial intelligence and distributed computation, in which many computers work together to solve problems. In his book, he contrasts A.I.’s way of learning with ours. An A.I. can be astonishingly smart, and even think intuitively, kind of like a person. But A.I. systems, Valiant argues, are not as flexible as human minds because they are not yet educable. Even the most state-of-the-art A.I.s learn through a rigid process, in which they are trained, at great expense, and don’t really get any smarter after that, no matter how much new information they ingest. It’s as though their minds freeze on graduation day. Yet human beings constantly improve their own minds through an unfolding, open-ended process that connects newly acquired facts and ideas to ones collected long ago. We “combine pieces of knowledge gained years apart” into “theories of considerable complexity that have many and disparate parts.”</p>
    <p>瓦里安特因其奠定人工智能和分布式计算 (多台计算机协同解决问题) 基础思想的贡献，荣获有计算机界诺贝尔奖之称的2010年图灵奖，他在书中将人工智能的学习方式与人类学习方式进行对比，人工智能可以非常聪明，甚至像人一样进行直觉思考，但是瓦里安特认为，人工智能系统并不如人类思维灵活，因为它们还不能接受教育，即使是最先进的人工智能，其学习过程也十分死板，需要投入大量资金进行训练，之后无论接收多少新信息，都不会变得更聪明，就好像它们的大脑在毕业那天就冻结了一样，然而，人类却是通过一种不断展开且无休止的过程，将新获得的事实和观点与很久以前收集的观点相联系，从而不断提升自身，我们能把多年获得的知识碎片整合成复杂且各部分迥异的理论。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Valiant says that he tries not to use the word “intelligent” to describe people (in fact, he is “sometimes taken aback” when he hears others use it); instead, he is drawn to “valuable abilities that somehow involve learning and are not well captured by conventional notions of IQ.” An educable mind, he writes, can learn from books, lectures, conversations, experiences, and Zen koans—from anything, really—and notice when relevant aspects of almost forgotten knowledge reveal themselves. We admire aspects of someone’s educability when we say that they are a quick study, or identify them as “coachable,” but what really makes them educable is that they apply insights “for purposes not foreseen at the time of the study or the coaching”; educability is something like “street smarts”—a term which connotes the “uncanny ability to negotiate the practicalities of life”—and is closely related to having common sense. When people strike us as particularly “well-educated,” this might mean that they’ve had lots of school, Valiant writes, but it could also mean that they’re exceptionally educable, with the ability to “take good advantage of whatever educational opportunities arise, whether formal or informal.”</p>
    <p>瓦里安特说，他尽量避免用“聪明”来形容人（事实上，当他听到别人这样形容时“有时会感到惊讶”）；相反，他更倾向于描述那些“以某种方式涉及学习且无法用传统智商概念来衡量的‘有价值的能力’”。 他写道，可教育的心灵能够从书籍、演讲、对话、经历和禅宗公案——实际上，可以从任何事物中进行学习——并且能够注意到记忆中几乎要被遗忘的知识的相关方面。当一个人学东西很快或被认为“可调教”时，我们就会赞赏其可教育性，但真正让一个人具有可教育性的，是他们能够将洞察用于“学习或指导时未曾预见的目的”；可教育性类似于“街头智慧”——这个词暗示了“处理生活实际问题的不可思议的能力”——与常识密切相关。瓦里安特写道，当我们认为某人受过“良好教育”时，这可能意味着他们上学时间很长，但也可能意味着他们具有极高的可教育性，能够“充分利用出现的各种教育机会，无论是正式的还是非正式的”。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>We’d probably like it if our political leaders were more educable: they “often need to make judgments on matters well beyond the knowledge and experience they had when elected.” Valiant suggests that we value educability in doctors, too. Imagine that you feel a pain in your side. Is it appendicitis? It would be unwise, he writes, to rely on what you know about the disease, based on what a few people who’ve had it have told you; you’d want to talk to a physician who’s seen a thousand cases. A medical A.I. could also train by looking at thousands of cases; in fact, “if it has seen a million cases, a situation well beyond individual human experience, then it may make predictions that are stunningly better than our intuitions can even comprehend.” And yet “the reason we go to doctors is not just that they have seen a thousand cases of a disease,” Valiant argues. “It is that we believe doctors deliver further results.” The basis of that extra value is educability.</p>
    <p>我们或许希望政治领导人更善于学习：他们“常常需要在超出其被选时的知识和经验范围的事务上作出判断。 ”瓦里恩特还认为，我们也重视医生的学习能力。想象一下，如果你的一侧身体感到疼痛。是阑尾炎吗？他写道，仅仅依靠你从几个得过该病的人那里听来的知识是不明智的；你需要咨询一个见过一千个病例的医生。医学人工智能也可以通过观察成千上万个病例来进行训练；事实上，“如果它看过一百万个病例，这是超越个人经历的情况，那么它可能会作出远远超出我们的直觉所能理解的预测。 ”然而，“我们去看医生并不仅仅因为他们见过一千个病例，”瓦里恩特认为。“我们相信医生能提供进一步的结果。 ”而这种附加价值的基础就是可教育性。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Valiant doesn’t get into details, but we can imagine for ourselves the value that a hypothetical doctor’s educability might provide. Such a doctor might draw on a range of ideas and connections spanning years of learning. She learned about appendicitis in medical school, of course—and quickly concludes that you don’t have it. But maybe her brother happens to be an avid cyclist, and she notices you drinking from a water bottle emblazoned with a logo she recognizes from his bike. Wasn’t there an article online about how dangerous the city’s bike lanes have become? More generally, she’s also developed a new theory: she ought to ask more questions about the particulars of her patients’ lives. She asks if you’re a cyclist, discovers that you are, and eventually pinpoints the real issue—a bruised rib acquired in a fall, which you’ve not allowed to heal properly. Being educable, the doctor actually regards your case as an opportunity to learn, and is a better physician for it.</p>
    <p>瓦利恩特没有细说，但我们自己可以想象一个假设的可教育医生能带来多大的价值．这样的医生会运用多年学习中跨越各个理念和联系的广度．当然，她在医学院学过阑尾炎－并迅速得出你并不是这个病的结论．但她哥哥恰好是个狂热的自行车爱好者，她注意到你拿着一个她从他自行车上见过的标志的水瓶喝水．网上不是有篇文章说城市里的自行车道变得有多危险吗？更广泛地说，她还有个新理论：她应该多问一些关于病人生活细节的问题．她问你是不是骑自行车的人，发现你是，并最终找到了问题所在－由于跌倒造成的一根肋骨挫伤，而你并没有让它好好恢复．因为具有可教育性，这位医生实际上把你的病例当成了一次学习的机会，并因此成为一个更好的医生．</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>That’s a rather schematic, explicit example of educability; sometimes, Valiant seems to be describing something more diffuse, and perhaps more powerful. To a degree, the connections, recombinations, and new applications of knowledge involved in being educable are useful precisely because they aren’t obvious. Every so often, I learn a lesson in one part of life that seems to apply to another: when I swim down the beach, for example, I tend to look at the umbrellas on the sand and think that I’m making very little progress, and yet, later, when I switch from the front crawl to the backstroke, I’m often surprised by the distance that I’ve travelled between my glances at the shore. The discovery that incremental progress feels faster when you let it accrue before judging it has been useful to me in my writing (and also in motivating me to clean out the garage). A civil-engineering class I took in college, which focussed on the structural forces shouldered by bridges and skyscrapers, comes back to me with great regularity when I think about all sorts of things. Wind exerts its force along the length of a skyscraper, causing it to bend. Similarly, a new source of stress in your life can’t be compartmentalized; it increases the pressure everywhere. It’s interesting to see one’s mind through the lens of educability. It makes you wonder what other cross-pollinations have occurred.</p>
    <p>这是一种比较简化的、明确的例子，说明了可教育性；有时候，瓦利恩特似乎在描述一些更加模糊、或许也更有力的事情。 在一定程度上，可教育性所涉及的知识之间的联系、重新组合及新用途之所以有价值，恰恰是因为它们并不明显。 时不时地，我在生活中的一个方面学到的东西似乎可以应用到另一个方面：比如，当我沿着海滩游泳时，我常常看着沙滩上的遮阳伞，觉得自己的进展微乎其微，但后来当我从自由泳换为仰泳时，却常常惊讶于自己在两次望向岸边之间游过的距离。 这一发现本身——当你不去评判而任由进步不断累积时，这种进步的感觉会更快——对我的写作大有帮助（同时也有助于激励我把车库打扫干净）。 大学时我上过的一门土木工程课，主要讲授桥梁和摩天大楼所承受的结构力，这门课的内容在我思考各种问题时经常被我想起。 风力沿着摩天大楼的高度对其施加作用，使其弯曲。 同样，生活中新出现的压力源也无法被分隔开来，它会增加各处的压力。 从可教育性的角度来看待自己的大脑是一件很有趣的事。 它让你不禁猜想究竟还有哪些跨界融合已经发生。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Valiant thinks it might be useful to promote educability as an ideal. We could try to figure out how to measure and teach it in schools, or to encourage it in adults; at a time when accelerating technological change means there’s always more to learn, we might seek to create a more educable society in general. (That change will further accelerate if Valiant’s proposals for A.I. capable of “artificial educability” prove workable.) After reading his book, I thought, on a less exalted scale, about how I might improve my own educability. I concluded that I would seek to learn about a wider range of subjects, and simply try more things, trusting that my mind would someday knit it all together. I also figured that it couldn’t hurt to remind myself of what I’d already learned. Down in the basement, a few big bookshelves hold my reading from college and graduate school. “Middlemarch” is there, along with many other books that I didn’t understand then but have come to value with the passage of time. Reading widely about things that don’t seem immediately or practically useful, in the hope that what you learn now may prove meaningful later—that’s pretty much the definition of a liberal-arts education. Who knew that one of its best defenders would turn out to be a computer scientist?</p>
    <p>瓦里安特认为，将可教育性作为一种理想来提倡或许是有用的。我们可以尝试找出衡量和教学的方法，并在学校里实行，或者鼓励成年人这么做；在技术变革不断加速、总有新事物需要学习的时代，我们或许应该努力创造一个更加具有可教育性的社会。如果瓦里安特关于具备“人工可教育性”的人工智能的设想切实可行，那么这种变化将会进一步加快。读完他的书之后，我联想到自己，虽然规模较小，但还是思考了如何提高自身的可教育性。我得出结论：我要拓宽学习领域的范围，多尝试一些事情，相信有朝一日我的大脑会将这些全都联系起来。我还想到，提醒自己已经学到了什么，应该也是无害的。地下室里有几个大书架，上面摆满了我大学和研究生期间读过的书。《米德尔马契》就在那里，还有许多其他当时读不懂但现在随着时间流逝逐渐懂得欣赏的书。为了寄托希望，即你现在学到的东西以后可能会变得有意义，而去广泛阅读似乎并不直接或实际有用的东西——这差不多就是文科教育的定义了。谁会想到它最好的辩护者竟然是一个计算机科学家呢？</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>