<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>What Can We Learn from Menstrual Blood?</h1>
    <h1>月经血能告诉我们什么？</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>By drawing data out of tampons and pads, startups hope to shed light on poorly understood diseases.</h5>
    <h5>通过从卫生棉条和护垫中提取数据，初创公司希望对一些鲜为人知的疾病有所了解。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Initially, Naseri approached menstrual blood as an alternative to venous blood, and set out to see if it could be mined for traditional biomarkers—molecules that point to the presence of a condition or disease. She enlisted Paul Blumenthal, an expert in cervical-cancer prevention and a professor emeritus of obstetrics and gynecology at Stanford’s medical school, in her effort. At first, the pair struggled to find a lab that would analyze their samples. “There was an ick factor,” Naseri recalled; some blood labs said that they didn’t want menstrual blood in their analyzers. Naseri and Blumenthal eventually found a lab that would work with them, and were able to show that menstrual blood can be used to monitor hemoglobin A1C, cholesterol, inflammatory proteins, and thyroid hormones. “If it can be tested for in circulating blood, it’s highly likely that we can find it in menstrual blood,” Blumenthal said. In January, 2024, the F.D.A. approved the use of the Q-Pad to track hemoglobin A1C, which reflects long-term average blood sugar.</p>
    <p>起初，纳塞里将经血作为静脉血的一种替代品，并着手研究是否可以从中提取传统生物标志物——即能够表明某种状况或疾病存在的分子。她请来宫颈癌预防专家、斯坦福大学医学院妇产科荣休教授保罗·布鲁门索尔参与这项工作。起初，二人很难找到愿意分析他们样本的实验室。“有一种让人反胃的因素，”纳塞里回忆道；一些血液实验室表示不希望让经血进入他们的分析仪。纳塞里和布鲁门索尔最终找到了愿意与他们合作的实验室，并证明了可以用经血监测糖化血红蛋白A1C、胆固醇、炎症蛋白和甲状腺激素。“如果能在循环血液中检测到它，那么我们极有可能在经血中也能发现它，”布鲁门索尔说。2024年1月，美国食品和药物管理局批准使用Q-Pad监测糖化血红蛋白A1C，该指标反映了长期平均血糖水平。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Meanwhile, in exploring how period blood could behave like venous blood, Naseri and Blumenthal hit upon something only menstrual blood could do. Blumenthal has travelled to Kenya, Myanmar, and Mexico to train physicians on alternatives to the Pap smear, which screens for cervical cancer but is difficult to implement without adequate training and infrastructure. He quickly realized that menstrual blood, which sweeps through the uterus and cervix, was likely to carry the H.P.V. virus, which can cause the cancer. In 2022, he and Naseri completed a prospective study indicating that the Q-Pad was better at detecting high-risk strains of H.P.V. than either a Pap smear or a self-collected vaginal swab. In 2023, Qvin received F.D.A. clearance to test Q-Pad screening for high-risk H.P.V. in Thailand. Blumenthal now believes that the main challenge will be winning clinicians over to the idea that routine, in-person gynecological testing could be replaced by a mailed-in sample of menstrual blood. “It really is an approach,” he said. “It’s not just a test.”</p>
    <p>与此同时，在研究经血如何能够表现得像静脉血的过程中，纳塞里和布鲁门索找到了只有经血才能做到的事。布鲁门索前往肯尼亚、缅甸和墨西哥培训医生使用宫颈癌筛查的替代方法巴氏涂片检查，但如果没有足够的培训和基础设施，这项筛查很难实施。他很快意识到，流经子宫和子宫颈的经血可能携带着导致这种癌症的人乳头瘤病毒（ＨＰＶ）。２０２２年，他和纳塞里完成了一项前瞻性研究，表明与巴氏涂片或自我采集的阴道拭子相比，ｑ－ｐａｄ在检测高风险ＨＰＶ方面更为有效。２０２３年，ｑｖｉｎ获得食品和药物管理局批准，在泰国测试ｑ－ｐａｄ对高风险ＨＰＶ的筛查。布鲁门索现在认为，主要挑战将是说服临床医生相信，常规的面对面妇科检查可以被邮寄的经血样本所取代。“这确实是一种方法，”他说，“不仅仅是一项测试。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>NextGen Jane, the company that Cate Gogolak found online, took the opposite tack: they started by asking what made period blood biologically unique. After exploring the idea of developing a discreet test for sexually transmitted infections—gonorrhea, chlamydia, and the herpes virus can also hang out around the cervix—they pivoted to trying to create a diagnostic test for endometriosis. There were no diagnostic markers approved by regulatory authorities for the disease. But Ridhi Tariyal, the company’s C.E.O., realized that, because the uterine lining is exquisitely sensitive to changes in hormonal signalling, analyzing menstrual blood might reveal the mass hormonal disruptions that endometriosis is thought to involve. This was a new way of thinking about the uterus—as a dynamic organ whose response to hormones could be measured and interpreted. “A sentinel system,” Tariyal said.</p>
    <p>在网上找到这家公司的凯特·戈戈拉克（Cate Gogolak）采取了相反的方法：他们首先询问是什么让经血在生物上独一无二．在探索开发一种用于检测性传播感染（淋病、衣原体和单纯疱疹病毒也会潜伏在子宫颈周围）的隐秘测试的想法之后，她们转向尝试创建一种子宫内膜异位症诊断测试．对于该疾病，监管机构没有批准任何诊断标记．但是公司首席执行官里希·塔里亚尔（Ridhi Tariyal）意识到，由于子宫内膜对激素信号的变化极为敏感，分析经血可能会揭示与子宫内膜异位症相关的大量荷尔蒙中断．这是一种新的思考子宫的方式——作为一个可以测量和解释其对荷尔蒙反应的动态器官．“一个哨兵系统，”塔里亚尔说．</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In recent years, endometriosis has become a kind of poster disease for how medicine has gaslit women, prioritizing their ability to reproduce over their pain. Doctors have long punted its symptoms into the realm of the psychological; in the past, antidepressants were common frontline medications, and even now many patients are first sent to therapists. Even well into the nineteen-nineties, endometriosis was called “the career woman’s disease,” and a common “cure” was held to be pregnancy, which temporarily arrests menstruation and changes hormone levels in the body. Women today still report being advised by their doctors to “just get pregnant.”</p>
    <p>近年来，子宫内膜异位症成了医学界漠视女性疼痛、只重其生育能力这一问题的代名词。长期以来，该病症的症状被认为属于心理问题；在过去，抗抑郁药常常被当作首选药物，甚至时至今日，许多患者仍被首先送去咨询精神科医生。哪怕到了20世纪90年代，子宫内膜异位症还被称为“职业女性病”，而一种常见的“疗法”就是怀孕——因为怀孕可以暂时停止月经并改变体内的荷尔蒙水平。时至今日，仍有不少女性表示，她们得到的医生建议是“赶紧怀孕”。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>To Tariyal, endometriosis seemed an ideal target for a women’s-health startup. But unlike Qvin, which could build off of preëxisting tests designed for venous blood, NextGen Jane needed to develop an entirely new test for endometriosis; this test had to work with menstrual blood and would ideally be approved by the F.D.A. This would require standardizing the collection and handling of menstrual blood, and creating a diagnostic test for endometriosis known as a molecular assay. Then, they would need to validate the assay against surgical results from a new set of patients. “It’s very easy to be dismissive of ideas like using menstrual effluence as a diagnostic substrate,” Tariyal told me. “To go from that to actual clinical utility, useful clinical information, is a long road. And people are looking for proof.”</p>
    <p>在塔里亚尔看来，子宫内膜异位症似乎是一个适合女性健康初创公司的理想目标。但与能够利用已有静脉血检测技术的Qvin不同，“下一代简”需要开发一种全新的子宫内膜异位症检测方法；这种检测方法必须适用于经血，并且最好能得到FDA的批准。这需要标准化经血采集和处理流程，并开发一种用于子宫内膜异位症诊断、被称为分子分析的方法。然后，他们需要根据新一批患者的手术结果验证这种分析方法。“人们很容易就驳回使用经血作为诊断样本这样的想法，”塔里亚尔对我说，“要从这一想法出发，真正获得有临床应用价值、有用的信息，还有很长的路要走。而人们都在寻求证据。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In NextGen’s offices, in Oakland, California, Matt McElroy, a biologist, gestured to what looked a bit like a wine press. “Let’s go by the technical term—arbor press,” he told me. The solid cast-iron machine in front of him could be used to punch holes, crimp jewelry, or stamp leather. He removed a plastic vial from a bag marked “biohazard.” Inside was a blood-soaked tampon, immersed in a preserving solution, which had been air-mailed to NextGen’s Oakland lab by a woman the day before. It had now oxidized to a deep reddish-brown, like rust.</p>
    <p>在位于加州奥克兰的NextGen办公室里，生物学家马特?麦埃尔罗伊指着一个看起来有点像葡萄酒压榨机的东西说：“我们还是用技术术语来说吧——这是个压木机。 ”他面前这台由整块铸铁制成的机器可以用来打孔、固定珠宝或是给皮革做标记。 他从一个写有“生物危害”的包里拿出一个塑料小瓶，里面有一个浸满了血的卫生棉条，泡在保存液中。 这个样本是前一天一个女人通过空邮寄到NextGen在奥克兰的实验室的，现在已经氧化成了深红棕色，就像生了锈一样。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>McElroy fitted the cannister with a plastic plug, slid it into the machine’s metal vise, and then cranked a lever, crushing the porous cotton and releasing its contents. He decanted the resulting fluid, which was brown-red and opaque, like aged Merlot, into a test tube. “Looks good,” he said. He held the vial up to a poster showing a rainbow of possible solution colors; a darker hue meant a heavier flow, which meant more blood and uterine lining for the lab to analyze. This one was a C4, out of a range of C1 to C5.</p>
    <p>麦克尔罗伊给容器装上一个塑料塞，把它放进机器的金属虎钳里，然后扳动一个手柄，多孔的棉花被压碎了，释放出它的内容物。他把得到的液体——红棕色，浑浊，像陈年的梅洛葡萄酒——倒进一个试瓶。“看起来不错，”他说。他把瓶子举起来，对照一张显示各种可能溶液颜色的挂图；更深的颜色意味着流量更大，这意味着实验室有更多的血液和子宫内膜可以分析。这一瓶是C4，在从C1到C5的范围内。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Gogolak, who after sending in her tampons had become an intern at NextGen Jane, stood with us in the lab. “We’re going to have an ombré,” she said, looking at a vial containing fluid the hue of a medium rosé. The samples would now be spun down in centrifuges, and then treated to filter out other proteins, tissue, and cell debris, until they contained only pure genetic material. Most of this would be banked in an industrial freezer rather than analyzed immediately: NextGen hopes to use its menstrual library to build an understanding of “normal” menstruation and develop future tests. Meanwhile, after ten years spent gathering and analyzing thousands of samples, the company believes it has identified an assay of forty-seven biomarkers which can reliably distinguish confirmed endometriosis patients. It is now beginning a validation study to confirm those results.</p>
    <p>戈加勒克在邮寄出卫生棉条后成为了NextGen Jane的一名实习生，她站在我们中间，在实验室里。“我们要得到的样本将会是渐变色的，”她说着，望向一个中等玫瑰红颜色的装有流体的小瓶。这些样本现在将要在离心机里旋转，然后进行处理以过滤掉其他蛋白质、组织和细胞碎片，直到只剩下纯净的遗传物质。这些样本中的大多数会被储存在一个工业用冰柜中而不是立刻被分析：NextGen希望利用其经血库建立起对“正常”经期的认识，并研发未来的测试。同时，在花了十年时间收集并分析了成千上万个样本之后，该公司认为他们已经确定了一组47个可以可靠区分已确认子宫内膜异位症患者的生物标志物。目前它已经开始了一项验证研究以确认这些结果。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In the end, the samples Gogolak sent to NextGen Jane were marked “suspected,” as her endometriosis had neither been confirmed nor denied through surgery. While she still holds out hope for an answer, she knows she won’t receive more information until the company is able to release a validated test—which Tariyal says is eighteen months away.</p>
    <p>最终，Gogolak寄给NextGen Jane的样本被标注为“疑似”，因为Jane的子宫内膜异位症尚未通过手术得到确认或否定。虽然她仍在期待一个答案，但她知道在公司推出验证测试前，她是得不到更多信息了—而Tariyal表示这需要十八个月的时间。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>“If you had a diagnosis, how would that help you?” McElroy asked her.</p>
    <p>“如果你有了诊断，那对你有什么帮助呢？ ” 麦克艾尔罗伊问她道。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>She paused, considering. If she’d been able to take a menstrual-blood test back in her freshman year, when her endocrinologist had had a hunch, it might have changed her path entirely, saving her years of expensive testing and weeks spent bedridden and on opioids. If the test had come back positive, it would have pointed her toward surgery years earlier; if it had come back negative, it would have suggested the need to look for another diagnosis. Instead, she was trapped in what Tariyal calls “analysis purgatory”—the agony of neither knowing nor not knowing.</p>
    <p>她停顿了一下，思考着这个问题。如果早在大学一年级的时候，她能够进行一次经血检测——当时她的内分泌学家就有这样的直觉——那么她的整个经历或许会完全不同，这能让她省下数年昂贵的检查费用和卧床吸食鸦片酊度日的几周时间。如果测试结果是阳性，就能让她提前几年去做手术；如果测试结果是阴性，则提示她需要寻找其他的诊断结果。相反，她被困在了塔里亚尔所称的“分析炼狱”中——一种既不能确定又不能否定的痛苦中。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Months later, Zooming with me from her dorm room, Gogolak lifted her sweatshirt to show me two patches on her midriff that were connected to a square device. Developed by a company called Livia, the tool creates vibrations to help relieve period pain. Next to her door was a portable heating pad, which she grabs on her way to class in the morning when her cramps are at their worst. After her pain and bleeding returned, in September, 2022, she and her parents scheduled a surgery—but then a new birth-control medication started working unexpectedly, bringing her symptoms under control. Still, if she forgets to take her birth control or progesterone for even one day, she can feel the nauseating pulling start to come back.</p>
    <p>几个月后，戈戈拉克在宿舍里和我视频通话时，她撩起运动衫，给我看她腰部连接着一个方形设备的两块贴片。这种由一家名为Livia的公司开发的工具通过振动来帮助缓解痛经。在她门边有一个便携式热水袋，当她的痛经最严重的时候，她会在早上上课时带上它。在2022年9月她的疼痛和出血复发之后，她和父母安排了一次手术——但随后一种新的避孕药出乎意料地开始奏效，使她的症状得到了控制。尽管如此，如果她哪怕有一天忘记服用避孕药或孕酮，她也会感到那种令人作呕的拉扯感开始卷土重来。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Gogolak still assumes that, at some point, she’ll have surgery. Today, her fear isn’t that surgeons will find endometriosis but that they will find nothing. In that case, she’ll be back to square one. “I just want to fully, one-hundred-per-cent know I have it or not,” she said.</p>
    <p>戈加拉克仍然认为自己迟早要动手术；现在她害怕的不是医生们会发现子宫内膜异位症，而是怕他们什么都发现不了，那样的话，她就又回到了原点：“我就是想百分之百地确定自己到底有没有这个病，”她说。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>A truly diagnostic noninvasive test for endometriosis—a test that can lead to a medical decision—may be years away. In the near term, what’s more likely is a screening test—a test that, like a mammogram or Pap smear, can tell you whether you have a high likelihood of having the disease. Yet screening tests have limitations, especially for diseases that aren’t well understood. The Pap smear or H.P.V. test can be incredibly useful because, if you detect cancer or pre-cancer early, you can start down the road to treatment and cure. There is no equivalent road for endometriosis. “The question is, How would this change our recommendations to patients?” Tami Rowen, an ob-gyn who specializes in benign gynecologic diseases, told me.</p>
    <p>真正具有诊断意义的非侵入性检查方法可能还需很多年才能问世。短期内，更有可能出现的是筛查测试，就像乳房X光检查或巴氏涂片检查一样，这种测试可以告诉你你患病的可能性有多大。然而，筛查测试也有局限性，尤其是对于那些尚未被充分了解的疾病来说。巴氏涂片检查或H. P. V. 测试之所以极其有用是因为，如果能早期发现癌症或癌前病变，就能及时开始治疗并最终治愈。但子宫内膜异位症却没有这样有效的疗法。“问题在于，这是否会改变我们给患者的建议？”专门研究妇科良性疾病的妇产科医生塔米·罗温告诉我。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Even if Gogolak received a definitive diagnosis of endometriosis through surgery, that diagnosis would not tell her which of several treatment options is most likely to work for her. Contraceptive pills can stop working, and even surgery is often not a cure. Another option, if birth control fails to control the symptoms, is a stronger cocktail of drugs that tamp down reproductive hormones; these can suppress menstruation, lower circulating estrogen, and quiet the reproductive system, often plunging a patient into temporary menopause. Such hormonal treatments haven’t changed significantly in forty years. They often come with severe side effects, and it can’t be known in advance whether they will work.</p>
    <p>即使戈戈拉克通过手术得到了子宫内膜异位症的确诊，这种诊断也不能告诉她哪一种治疗方法对她最有效。避孕药可能会失效，而手术也常常不能治愈疾病。如果避孕措施无法控制症状，那么可以采用更为强烈的药物组合来抑制生殖激素；这些药物能够抑制月经、降低血液中的雌激素水平，并使整个生殖系统平静下来，这往往会令患者进入暂时性的更年期。在四十年里，这样的激素疗法并没有显著的变化。它们常常伴随着严重的副作用，而且无法预知是否有效。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Christine Metz, a reproductive biologist at Northwell Health, on Long Island, is the co-director of ROSE, another research team developing an endometriosis test based on menstrual blood. She told me that, when it comes to endometriosis and other benign gynecological diseases, the knowledge gap goes further than diagnosis. For example, although birth control is widely held to slow down the progression of the disease, there is little evidence that it does so: Metz said that nearly every clinical trial to date on endometriosis treatment, whether surgical or hormonal, has measured not the progression of the disease as such but, rather, relief from pain. “It’s pain, pain, pain,” Metz pointed out. “It’s like if you asked cancer patients how they’re feeling after they took chemotherapeutic agents.”</p>
    <p>长岛诺斯韦尔健康中心的生殖生物学家克里斯蒂娜·梅茨是“卵巢内分泌研究联盟”另一支致力于根据经血来检测子宫内膜异位症的研究团队的联合主任。她告诉我，关于子宫内膜异位症和其他良性妇科疾病的知识空白远不止诊断方面。例如，虽然普遍认为避孕措施能够延缓病情发展，但几乎没有证据支持这一观点：梅茨称几乎每一项关于子宫内膜异位症治疗（无论是手术还是激素疗法）的临床试验衡量的都不是病情本身的发展情况，而是疼痛的缓解程度。“就是疼，疼，疼，”梅茨指出，“这就相当于去问癌症患者在他们服用了化疗药物后感觉如何。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>When it comes to historically misunderstood diseases like endometriosis, there are still more unknowns than knowns. Yet the work that companies like NextGen Jane and Qvin are doing lays the foundation for an expansion in our knowledge. By probing how the uterus responds to hormonal shifts, and by learning the full composition of menstrual blood and how it changes over time, they may make more rigorous research into endometriosis and other reproductive diseases possible. Drop by drop, they are painting a fuller picture of an area of the body that’s been hidden for too long.</p>
    <p>说到子宫内膜异位症等历史上长期被误解的疾病，我们仍然未知的东西多于已知。但NextGen Jane和Qvin等公司所做的工作为扩展我们的知识奠定了基础。通过探索子宫对激素变化的反应，以及了解经血的全部成分及其随时间的变化，它们可能使针对子宫内膜异位症及其他生殖系统疾病的严谨研究成为可能。一点一滴地，它们正在描绘一幅长期以来隐藏于人们的这一身体部位的完整图景。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>