<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h2>Kamala Harris and the Legacy of Bidenomics</h2>
    <h2>卡玛拉·哈里斯与“拜登经济学”遗产</h2>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>How the Vice-President’s economic approach might build upon, and differ from, that of her predecessor.</h5>
    <h5>副总统的经济方式会怎样在其前任的基础上构建而又有所不同。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Now that Kamala Harris has effectively wrapped up the Democratic nomination for President, journalists and pundits are examining her every word for clues about how she might govern. To some extent, the answer is obvious. Having served for four years under Joe Biden, the Vice-President would seek to extend his Administration’s policy accomplishments, which she described last week as “unmatched in modern history.” But, on the economy, what exactly is the Biden legacy?</p>
    <p>随着卡玛拉·哈里斯实质上已锁定民主党总统提名，记者和评论员正仔细推敲她的一言一行，试图从中寻找她执政方式的线索。在某种程度上，答案显而易见：作为乔·拜登的副总统，哈里斯会寻求延续其政府的政策成果，而她上周刚刚将这些成就描述为“现代史上绝无仅有”。但话说回来，拜登的经济遗产究竟是什么呢？</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In a report published last November, the Roosevelt Institute, a progressive think tank based in New York, pointed out that the defining goal of Bidenomics, its “North Star,” has been to rebalance the economy, moving power away from large corporations toward workers and consumers. This principle has guided many of the Biden Administration’s economic actions: using stimulus policy to promote strong job growth and low unemployment, which strengthens the bargaining power of workers; enforcing labor laws and making it harder for companies to thwart unionization drives; using antitrust statutes to contain the monopoly power of big corporations in industries ranging from high tech to supermarkets to airlines. “Empowering workers and curbing corporate power—that is the essence of the Biden legacy,” Felicia Wong, the president of Roosevelt Forward, the advocacy organization affiliated with the institute, and a co-author of the report, told me. “The big question going forward is: How long will that last?”</p>
    <p>去年 11 月发布的一份报告中，位于纽约的自由派智库罗斯福研究所指出，拜登经济学的核心目标——或者说其“北极星”——一直是重新平衡经济，将权力从大企业转移到工人和消费者手中。这一原则指导了拜登政府许多经济行动：利用刺激政策促进强劲的就业增长和低失业率，从而增强工人的议价能力；严格执行劳动法，让企业更难阻挠工会组织活动；运用反垄断法规约束从高科技到超市再到航空业等各行业大企业的垄断势力。“赋予工人权力、限制企业势力——这就是拜登执政理念的核心。”该报告的合著者、与该研究所有关联的倡议组织“前进中的罗斯福”的负责人费利西亚·翁格对我说，“接下来的大问题是：这种状态能持续多久？”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The answer depends on the result of the election, of course. Donald Trump has promised to roll back much of Bidenomics, including its subsidies for green energy and electric vehicles. If Harris wins, these policies, and many others, will remain in place. Bharat Ramamurti, who served as the deputy director of the National Economic Council from 2021 to 2023, told me that the over-all Biden-Harris economic agenda “is likely to persist, in part because it is reflective of the Vice-President’s input.” During Ramamurti’s time in the White House, he worked with Harris and her staff on a number of issues, including reducing medical-debt burdens, broadening broadband access, and making sure that small-business owners, including minority ones, gained access to COVID-relief funds. Harris, he said, was interested in practicalities: “I think her focus tended to be on, How is this stuff going to work?”</p>
    <p>答案当然取决于选举结果。唐纳德·特朗普已经承诺要取消拜登经济学的许多内容，包括对绿色能源和电动汽车的补贴。如果哈里斯胜出，这些政策以及许多其他政策都将保持不变。巴拉特·拉马穆尔蒂在2021年至2023年担任国家经济委员会副主任，他告诉我，“总体而言，拜登-哈里斯的经济议程可能会延续下去，部分原因是它反映了副总统的观点。”在拉马穆尔蒂于白宫任职期间，他就一些问题与哈里斯及其团队进行了合作，这些问题包括减轻医疗债务负担、扩大宽带接入范围，以及确保小企业主（包括少数族裔企业主）能够获得新冠疫情救助资金。他说，哈里斯关注实际问题：“我认为她的注意力往往集中在这些事情如何才能行得通上。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>A President Harris would probably prioritize enacting elements of Biden’s Build Back Better agenda that failed to make it through Congress in 2021 and 2022, such as paid medical leave and universal pre-kindergarten. Speaking to campaign workers last week, she said, “We believe in a future where no child has to grow up in poverty . . . and where every person has access to paid family leave and affordable child care.” In policy circles, many of these proposals fall under the rubric of “the care economy”—a term likely to be repeated many times in the coming months. Harris was personally committed to it even before she became Biden’s running mate, in 2020. And it potentially provides a way for her to distinguish her policy platform from Biden’s in a manner that is consistent with his approach, but which could also help her shore up Democratic support, especially among women and minority voters.</p>
    <p>哈里斯总统可能会优先实施拜登“重建更美好”议程中那些在2021年和2022年未能获得国会通过的部分，比如带薪医疗休假和普及学前班教育。上周，她对竞选工作人员说：“我们相信一个不让任何儿童生活在贫困中的未来……而且每个人都能够享有带薪家庭休假和负担得起的儿童保育服务。”在政策圈里，许多此类提议都属于“关怀经济”的范畴——在未来几个月里，人们可能会反复听到这个术语。早在2020年成为拜登竞选搭档之前，哈里斯就已亲自致力于此。而这也可能为她提供一条途径，在不偏离拜登方针的情况下，将她的政策纲领与拜登区分开来，同时也有助于她赢得民主党人的支持，尤其是女性和少数族裔选民的支持。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In 2018, then-Senator Harris proposed a refundable tax credit for lower- and middle-income families, which would have provided cash payments of two hundred and fifty dollars a month for single tax filers and five hundred dollars a month for married couples. As Vice-President, she was a vocal supporter of the expanded child tax credits introduced in the American Rescue Plan Act, passed in March, 2021, which led to a dramatic reduction in the child poverty rate until they lapsed at the end of that same year. Pushing for a permanent expansion of child tax credits seems likely to be a significant feature of Harris’s policy platform.</p>
    <p>2018 年，当时的参议员哈里斯提出一项可退还的税收抵免政策，面向低收入和中等收入家庭，这项政策将为单独报税者每月提供 250 美元的现金支付，为已婚夫妇每月提供 500 美元的现金支付。作为副总统，她公开支持《美国救援计划法案》中推出的扩大儿童税收抵免措施，该法案于 2021 年 3 月通过，在同年年底过期前显著降低了儿童贫困率。推动永久性扩大儿童税收抵免很可能会成为哈里斯政策纲领的一个重要特征。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>She may well also resurrect the federal Domestic Workers Bill of Rights, which she co-sponsored in 2019 with Representative Pramila Jayapal. This bill addressed a long-standing inequity: the exclusion of domestic workers—direct-care workers, nannies, and house cleaners—who now number about 2.2 million, from the labor protections that were enshrined for other workers during the New Deal. The 2019 legislation, which didn’t go anywhere, would have righted that wrong by making minimum-wage laws and maximum-hours limits apply to care workers. It would also have guaranteed them paid time off, safe working conditions, and protection from discrimination. “The Vice-President has been one of our biggest champions,” Jenn Stowe, a senior adviser to the advocacy group Care in Action, told me. “She understands that these workers, who are overwhelmingly people of color and immigrants, deserve to be seen, to be treated with dignity, and to have the same rights and protections as other workers.”</p>
    <p>她也很可能会重提联邦《家政工人权利法案》,该法案由她和众议员普拉米拉·贾亚帕尔在2019年共同发起。该法案针对的是一个由来已久的不公——家政工人（包括直接护工、保姆和清洁工）如今大约有220万人，长期被排除在新政时期为其他工人确立的劳动保护之外。2019年的这项未能通过的立法本可以通过将最低工资法和最高工时限制适用于护工行业来纠正这一错误。它还将保障这些工人的带薪休假、安全工作环境以及免受歧视的权利。“副总统一直是我们最强大的支持者之一，”倡导组织“行动关怀”高级顾问詹·斯托告诉我，“她明白这些工人绝大多数是有色人种和移民，他们理应得到认可，理应得到尊重，并且应该享有与其他工人相同的权利和保护。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>I spoke with a former senior adviser to Harris who predicted that, should she become President, she would also focus on housing and labor issues. As a politician from California, she has long recognized the prominence of affordable-housing issues, and in the White House she headed an interagency task force on worker organizing and empowerment. She has also spoken at many labor-union events, the latest of which was an American Federation of Teachers convention in Houston, last week. “That’s who she is,” the former adviser said. “She’s trying to help workers in the belief that they build up the entire economy.”</p>
    <p>我之前和哈里斯的一位前高级顾问聊过，他预测如果她成为总统，也会重点关注住房和劳工问题。作为来自加州的政治人物，她一直很重视可负担住房问题，在白宫时，她还牵头了一个关于劳工组织和赋权的多机构特别工作组。她还参加过很多工会活动，最近一次是上周在休斯敦举行的美国教师联合会大会。“这就是她的为人，”那位前顾问说，“她想帮助劳工，因为她相信他们能促进整个经济的发展。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>If this testimonial echoed Biden’s oft-repeated pledge to build the economy “from the middle out and the ground up,” it shouldn’t be surprising. In some circles, however, doubts have been raised about Harris’s commitment to a key part of Biden’s rebalancing agenda: moves by the Justice Department and the Federal Trade Commission to block corporate mergers that endanger competition and to investigate and sue giant tech firms that abuse their market dominance.</p>
    <p>如果这段证词呼应了拜登时常重申的从“中间和底层”重建经济的承诺，那倒也不足为奇。然而，在某些圈子里，人们还是对哈里斯在拜登再平衡议程的关键部分——即司法部和联邦贸易委员会阻止危害竞争的企业合并、调查并起诉滥用市场主导地位的科技巨头——上的投入有所怀疑。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Last week, in a Substack post, Matt Stoller, the research director at the American Economic Liberties Project, which focusses on monopoly issues, pointed out that Harris, when she was attorney general of California, had cordial relationships with many Silicon Valley executives, and that she still has ties to the tech industry. Later in the week, Reid Hoffman, a Silicon Valley billionaire who is a major Democratic donor, and who is reportedly slated to do a campaign fund-raising tour with the Vice-President, caused a stir by telling CNN that he hopes she would replace Lina Khan, whose term as the F.T.C.’s commissioner expires in September. A couple of days later, the media mogul Barry Diller, another Democratic donor, said something very similar.</p>
    <p>上周，在“Substack”网站的一篇帖子中，美国经济自由计划的研究主管马特·斯特勒指出了这样一点：当哈里斯担任加州司法部长时，她与硅谷的许多高管都保持着友好关系，而她至今仍与科技行业保持着联系。美国经济自由计划是一个专注于研究垄断问题的组织。同一周晚些时候，硅谷亿万富翁里德·霍夫曼在接受美国有线电视新闻网采访时说，他希望哈里斯能在九月接替任期届满的联邦贸易委员会专员莉娜·可汗。霍夫曼是民主党的一位重要捐助人，据报道他将陪同副总统开展巡回筹款活动。霍夫曼这番话引起了一阵轰动。几天后，媒体大亨巴里·迪勒——另一位民主党的捐助人——说了类似的话。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The Harris campaign hasn’t issued any comment on the donors’ statements or whether the Vice-President supports Khan’s reappointment. But Senator Bernie Sanders described Hoffman’s call to replace Khan “unacceptable”; Senator Elizabeth Warren issued a statement of support for Khan; and Tim Wu, a Columbia Law School professor who worked at the White House on competition issues from 2021 to 2023, said on X that the Harris campaign should return Hoffman’s donations.</p>
    <p>哈里斯的竞选团队尚未就捐赠者的言论或副总统是否支持汗的连任发表任何评论。但伯尼·桑德斯参议员形容霍夫曼要求替换汗的言论“不可接受”；伊丽莎白·沃伦参议员发表声明支持汗；哥伦比亚法学院教授蒂姆·吴曾在2021年至2023年间在白宫负责竞争问题，他在X上表示哈里斯的竞选团队应当归还霍夫曼的捐款。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>