<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>What Don’t We Know?</h1>
    <h1>我们还都不知道什么？</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>We have a lot to learn from studying our ignorance.</h5>
    <h5>从对我们无知的研究中 我们有许多可学的</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>My son, who is at pains to tell you that he is not five but five and three-quarters, is obsessed with the future. He draws pictures of crystalline cityscapes crisscrossed by “hyperloops” and flying cars; in the future, he says, scientists will “wreck down” our house to build a skyscraper, and robots will take the place of police officers. He’s certain about all this but uncertain when it will happen. Last year, he thought the future might arrive in 2024; he’s now considering 2025, or even later. “What if it takes them a really long time to build the future?” he asked me the other night, with a concerned look. “What if it takes until I’m an old man?” (I winced to hear him say those words.) “Or what if I die”—he mimed a kind of heart attack—“and I miss it?” I did my best and told him that he will definitely see at least some of “the future,” as he pictures it, when he grows up.</p>
    <p>我的儿子急着告诉别人他不是五岁，而是五岁零三个月大，他对未来迷恋不已。他画出晶莹剔透的城市风光，到处是“超级高铁”和会飞的汽车；他说将来科学家会把我们的房子“拆掉”，盖起摩天大楼，而机器人也会取代警察。这一切他都坚信不疑，只是不确定这一切何时会发生。去年他认为可能是 2024 年，现在他又觉得可能是 2025 年，甚至更晚。“要是建造未来花费的时间特别长怎么办？”有天晚上，他一脸担忧地问我，“要是要等到我老了才建成怎么办？”（听见他说老这个字眼，我心里一紧）“或者要是我死了”——他比划了一个心脏病发作的动作——“错过了这一切怎么办？”我尽力安抚他，告诉他长大后肯定会看到他所想象的那个未来的至少一部分。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The truth, of course, is that we’re ignorant about the future. Who will win the election in November? Will we lose our jobs because of A.I.? Will the planet boil or merely simmer? What will skyscrapers, or smartphones, or schools look like in thirty years? We’re not in the dark about these questions; we can make educated guesses or predictions. But there’s an odd way in which, the more informed our speculations become, the more they serve to highlight what we don’t know. “The knowledge we possess determines the degree of specificity of the ignorance we recognize,” the philosopher Daniel DeNicola writes, in his book “Understanding Ignorance.” The more you know, the more precisely you can say what you don’t.</p>
    <p>当然，事实是我们对未来一无所知。11月的选举谁会赢？我们会因为人工智能而失业吗？地球最终会沸腾还是会仅仅冒泡？三十年后摩天大楼、智能手机和学校会变成什么样子？对于这些问题我们并非一无所知；我们可以做出有根据的猜测或预测。但奇怪的是，我们的推测越是经过深思熟虑，就越发凸显出我们的无知。“我们所掌握的知识决定了我们所能认识到的无知的具体程度，”哲学家丹尼尔·德尼科拉在其著作《理解无知》中写道。你知道得越多，就能越精确地说出自己不知道什么。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>DeNicola’s book is an entry in a subfield of philosophy called “agnotology”—the study of ignorance. As philosophical subfields go, agnotology sounds abstract and even a little contradictory: what could it even mean to study what’s unknown? And yet, because ignorance is actually an everyday condition from which we all suffer, the study of it is quite down to earth. Have you ever been in a bookstore, leafed through a weighty tome, and then returned it to the shelf? You are practicing “rational ignorance,” DeNicola writes, by making “the more-or-less conscious decision that something is not worth knowing—at least for me, at least not now.” (In an information-rich society, he notes, knowing when to maintain this kind of ignorance is actually an important skill.) Have you ever tuned out a gossipy friend because you don’t want to know who said what about whom? Deciding that you’d rather be above the fray is “strategic ignorance”; you embrace it because it will make life better, deploying it when you decide not to read the reviews before seeing a movie, or conduct a hiring process in which the names of the candidates are obscured. There’s a big difference between strategic ignorance and what DeNicola calls “involuntary” ignorance: “In the iconic image, Justice is blindfolded, not blind,” he writes.</p>
    <p>德尼科拉的书为哲学的一个分支领域——“无知学”添上了浓墨重彩的一笔。在哲学的分支领域中，“无知学”听起来有些抽象，甚至还有些自相矛盾：研究未知事物究竟是什么意思？然而，由于无知实际上是我们每个人都深受其苦的一种日常状态，因此对它的研究十分接地气。你有没有过这样的经历：在书店里随手翻阅一本厚重的大部头，然后又把它放回书架？德尼科拉写道，你这是在实行“理性无知”，即“或多或少有意识地决定某事不值得了解——至少对我来说是这样，至少现在是这样。”（他指出，在信息丰富的社会中，知道何时保持这种无知其实是一项重要的技能。）你有没有过这样的经历：因为不想知道谁说了关于谁的什么话，所以就不理会某个爱说闲话的朋友？决定置身事外就是“策略性无知”；你之所以选择它是因为这样做会让生活更美好，在决定看电影前不看影评，或者在招聘过程中对候选人的姓名保密时，就会用到它。策略性无知与德尼科拉所说的“非自愿”无知之间存在着巨大差异：“在标志性的形象中，正义是被蒙住了双眼，而不是看不见东西，”他写道。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>My wife’s parents have a box of letters that were sent between her grandfather and her grandmother while he was serving in the Navy during the Second World War. The box is in the basement; no one has read the letters, and no one plans to. This reflects a valid concern for privacy, but it also involves what DeNicola calls “willful ignorance”—the persistent, long-term maintenance of a gap in one’s knowledge that could easily be filled in. Willful ignorance isn’t necessarily bad; it might be wise to avoid learning the disturbing details of a half-forgotten traumatic event, for instance, lest they keep the trauma fresh. But we should be wary of willful ignorance, DeNicola argues, because it often flows from fear. “Consider a mother who is so upset about her son’s military service that she refuses to discuss it while he remains on active duty,” DeNicola writes. Or a voter who refuses to read about a favored candidate’s ongoing scandal. “The benefits of willful ignorance tend to be overestimated by those who exhibit it”; knowledge can be a path to overcoming fear.</p>
    <p>我妻子的父母存有一盒信件，这些信是我妻子的外祖父和外祖母在二战期间她外祖父服役于海军时互相寄给对方的。这盒信放在地下室里；没有人读过这些信，也没有人打算去读。这反映了人们对于隐私的一种合理的顾虑，但也体现了德尼科拉所说的“刻意无知”——即长期坚持维护自己知识中能够轻易填补的空白。刻意无知未必是坏事；比如，避免了解一件半被遗忘的创伤事件令人不安的细节或许不失为明智之举，以免这些细节让创伤记忆常新。但德尼科拉认为，我们应该警惕刻意无知，因为它往往源于恐惧。“试想一位母亲对自己儿子服兵役这件事感到非常苦恼，以至于在其儿子服役期间拒绝讨论此事，”德尼科拉写道。或者，一位选民拒绝了解自己支持的候选人所涉及的持续发酵的丑闻。“那些表现出刻意无知的人往往会高估刻意无知的好处”；知识可以成为克服恐惧的一条途径。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>DeNicola argues that, even when we don’t choose ignorance, there are ways in which we must “dwell in ignorance,” no matter what we do. We’re ignorant of most of what happened in the past because, despite our efforts at historical reconstruction, “worlds disappear” in the flow of time. We’re ignorant about the future not just because we don’t know what will happen but because we lack the ideas needed to comprehend future knowledge: “Galileo could not have known that solar flares produce bursts of radiation,” for example, because the very idea of radiation depends on a “framework of theoretical concepts” that wasn’t developed until hundreds of years after he lived. It turns out that there’s a special word, “ignoration,” which describes the condition of people who “do not even know that they do not know.” In a broad, almost existential sense, we all live in ignoration all the time. Recognizing this makes knowing what you don’t know feel like a step forward—even an opportunity to be seized.</p>
    <p>德尼科拉认为，即便我们没有主动选择无知，也总有某些时候我们不得不“生活在无知之中”，无论我们做什么都是如此。我们对过去所知甚少，因为我们尽管努力重构历史，“但世界已在时光流逝中消失不见”。我们对未来所知甚少不仅仅是因为我们不知道将要发生什么，还因为我们缺乏理解未来知识所需的概念：“伽利略不可能知道太阳耀斑会产生辐射爆发”，因为“辐射”这一概念依赖于一套“理论概念体系”，而后者是在他去世几百年后才建立起来的。原来，还专门有一个词，“ignoration”，来形容那些“连自己不懂什么都不清楚”的人。从某种宽泛的、几乎是形而上的意义上来讲，我们所有人一直生活在“ignoration”之中。意识到这一点会让人觉得，知道自己不知道什么其实是一种进步——甚至是一个值得把握的机会。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>One of the benefits of studying your ignorance, DeNicola shows, is that you can calibrate it. Maybe you’d like to be less ignorant about your mother’s job, or more ignorant about your roommate’s relationships. DeNicola asks us to imagine a man who goes to a new restaurant and orders the soup. It’s delicious! But the restaurant serves a strange cuisine from a country that he’s never visited, and he’s a picky eater. He might decide that he doesn’t want to know what’s in the soup. The problem is that the acceptability of our ignorance depends on our identities and goals. What if he’s a vegetarian? In that case, he might be compromising his principles by not knowing the ingredients. What if he has a food allergy? He might be taking a deadly risk. In Henry James’s novel “The Portrait of a Lady,” an heiress named Isabel Archer moves from America to Europe, where she falls for and marries Gilbert Osmond, another expat who seems especially sensitive and refined. Unsure of herself and decorous to a fault, Isabel doesn’t ask too many questions about Osmond’s past; she doesn’t press him, for instance, for the name of the mother of his fifteen-year-old daughter. And of course Isabel discovers, eventually, that Osmond has married her for her money at the urging of his mistress, who is the girl’s mother. Isabel’s willful ignorance was miscalibrated. And yet you can’t always ask what’s in the soup.</p>
    <p>德尼科拉指出，研究自己的无知状态的好处之一是，你可以对自己的无知状态加以调整。 也许你希望自己对母亲的工作少一些无知，或者对室友的感情生活多一些无知。 德尼科拉让我们想象一个人走进一家新餐馆并点了一碗汤。 这汤真好喝！ 但是这家餐馆供应的是他从未去过的国家的奇怪食物，而他又是一个挑食的人。 他可能决定自己不想知道这汤里放了什么。 问题在于我们对无知状态的接受程度取决于我们的身份和目标。 如果他是素食主义者呢？ 在这种情况下，他不问汤的原料就是在违背自己的原则。 如果他对某种食物过敏呢？ 他可能会冒生命危险。 在亨利·詹姆斯的小说《一位女士的画像》中，一位名叫伊莎贝尔·阿切尔的女继承人从美国移居到欧洲，在那里她爱上并嫁给了另一位名叫吉尔伯特·奥斯蒙的侨民，此人看起来特别敏感且有教养。 由于对自己不够自信，加之过分讲究礼节，伊莎贝尔没有对奥斯蒙的过去问太多问题； 比如，她就没有追问谁是他15岁女儿的母亲。 当然，后来伊莎贝尔发现奥斯蒙是在情妇的怂恿下为了钱才娶她的，而他的情妇就是他女儿的母亲。 伊莎贝尔的故意无知是判断失误。 然而，你不可能总是问这汤里放了什么。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>After reading DeNicola’s book, I started a kind of ignorance audit of my life. I drew up a list of unanswered questions—a to-know list to go with my to-do list. What’s the name of the nurse who works Saturday and Sunday nights at my mom’s nursing home? What’s wrong with my back, such that I sometimes wake up to find my upper body canted a few degrees to the right? How much must the sea rise before it inundates the small town where I live, and when is that forecasted to occur? Whatever happened to my best friend in second grade? For obvious reasons, the list began to grow without bounds. Still, it felt a little liberating to articulate these questions. I was doing what DeNicola calls “locating the boundary of the known,” and giving myself a chance to venture beyond it.</p>
    <p>读了德尼科拉的书之后，我开始对我生活中无知的东西进行一种审计。我列出了许多未解的问题——一份“要知道”的清单来配合我的“要做”清单。在我母亲疗养院里周六周日值夜班的护士叫什么名字？ 我的背部到底怎么了，以至于我有时醒来会发现自己的上半身向右倾斜了几度？ 海平面要上升多少才会淹没我居住的小镇，这预计会在何时发生？ 我二年级时最好的朋友后来怎么样了？ 由于显而易见的原因，这些问题很快就无穷无尽起来。即便如此，能把这些问题讲出来还是让人感到些许解脱。我正在做德尼科拉所说的“确定已知事物的边界”的工作，并且给自己一个机会去超越这个边界。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In a recent book called “Sense, Nonsense, and Subjectivity,” a German philosopher named Markus Gabriel argues that our personhood is partly based on ignorance—that “to be someone, to be a subject, is to be wrong about something.” It’s intuitive to hold the opposite view—to say that we are the sum of what we know. But Gabriel points out that, even when you know something to be true, you probably also know that there are aspects of it about which you’re probably wrong. I encountered this phenomenon recently when my son asked me to explain the meaning of “E=mc2”—but, also, when I tried to tell him about how I’d met his mom. “We were riding up in an elevator, and we started talking, and then she got off,” I said. “And then, later, when I was riding down, she got back on.”</p>
    <p>在最近出版的一本书《理性、非理性和主体性》中，德国哲学家马库斯·加布里埃尔提出，人的个性部分基于无知——“成为一个个体，成为主体，意味着犯错”。我们直觉上会认为，我们的全部由我们的认知构成。但加布里埃尔指出，即使你知道某事是真的，你可能也知道，有关此事的某些方面你很可能是错的。我最近就遇到过这种现象，当时我的儿子让我解释“E=mc2”的含义——同样，当我试图告诉他我是如何遇到他妈妈的时候也是。“我们当时正在乘电梯上楼，然后就开始聊天，接着她就下去了，”我说，“后来，当我乘电梯下楼时，她又进来了。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>This story is true, but also wreathed in inevitable uncertainties. What exactly did we say to one another? What were we wearing, or thinking, or feeling, before and after? There are limits to recollection, and to noticing in the moment; life is short, and you can’t know it all, not even about yourself. But you can know, at least to some extent, what you chose not to know and what you wished you’d found out. You can understand what you looked away from, and toward.</p>
    <p>这个故事是真的，但也不可避免地笼罩在种种不确定性中。我们当时到底对彼此说了什么？在此之前和之后我们都穿了什么、想了什么、感受了什么？回忆总有极限，当下的留意也有限度；人生苦短，你不可能什么都了解，哪怕是你自己。但至少在一定程度上，你会明白自己选择不去了解什么，又希望自己能发现什么。你会明白自己回避了什么，又接近了什么。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>