<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>“Wrong Way” Takes the Shine Off the Self-Driving Car</h1>
    <h1>「反方向」让自动驾驶汽车光彩不再</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>Joanne McNeil’s novel suggests that much of what we think of as technological progress is a new way to obscure human labor.</h5>
    <h5>乔安娜·麦尼尔的小说表明，我们通常认为的技术进步大多不过是掩盖人力劳动的新方式。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Car companies have been experimenting with driverless cars for decades, but their presence on roads has exploded in recent years. It became increasingly common, beginning in the twenty-tens, to see robo-taxi prototypes driving around on public streets, albeit with human “safety drivers” sitting inside, ready to take over and compensate for machine error. Then the safety drivers started vanishing. Since last year, it has been possible to hail fully driverless taxis in Phoenix. Earlier this year, they hit the streets in San Francisco, and rollouts are planned in many other major American cities. It remains to be seen whether the robo-taxi companies have a path to profitability, how safe their vehicles will prove to be as time passes, and how regulators might respond. What’s undeniable is that, at least for the moment, they’re out there on our roads.</p>
    <p>汽车企业对无人驾驶汽车的试验已有数十年，但近年来这种汽车出现在公路上的数量激增。从2010年前后开始，人们越来越常见到无人驾驶出租车原型车在公共街道上行驶的情形，尽管车内仍坐着人类“安全驾驶员”，随时准备接手驾驶以防机器出现差错。随后，安全驾驶员开始消失不见。从去年开始，菲尼克斯已经可以叫到完全无人驾驶的出租车。今年早些时候，这种出租车出现在了旧金山街头，并计划在美国其他主要城市推出。这些无人驾驶出租车公司是否找到了盈利之路仍有待观察，随着时间推移，这些车辆的安全性如何也有待验证，监管机构将作何反应同样有待观察。但不可否认的是，至少目前它们已经出现在我们的道路上。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>This poses an interesting challenge for fiction. For sci-fi writers, driverless cars have long been a supremely efficient shorthand for dramatic change, an effective way of immediately grounding a story in the future, where things are different. The Czech American physician and author Miles J. Breuer’s 1930 novel, “Paradise and Iron,” is set largely on an island where most technology works without human input. The narrator gets a “queer feeling at the complete absence of wheel and gear-shift levers,” or any person operating them. Sci-fi storytellers have been leveraging that queer feeling ever since, often—in the case of movies—with help from carmakers. Audi helped design the autonomous cars in “I, Robot” (2004) and “Ender’s Game” (2013), which concretize the films’ visions of the future.. But what happens when a long-standing symbol of the future arrives in reality? How do you write about it?</p>
    <p>这对小说创作提出了一个有趣的挑战。对科幻作家来说，无人驾驶汽车一直是剧变的极其有效的象征，是让故事立即植根于未来——在那里一切都不同了——的一种有效方式。捷克裔美国医生、作家迈尔斯·J·布鲁尔1930年的小说《天堂与铁》大部分情节都发生在一个岛上，在那里大多数技术无需人类输入即可运作。叙述者“因为完全没有方向盘和换挡杆而感觉怪异”，或者根本没有人来操作这些部件。 科幻叙事者从此一直在利用这种怪异的感觉，而且往往在电影中还得到了汽车制造商的帮助。在《我，机器人》(2004)和《安德的游戏》(2013)中，奥迪帮助设计了自动驾驶汽车，这些汽车将影片对于未来的设想具体化了。 但是当一个长久以来的未来象征出现在现实生活中时会发生什么呢？你该如何去写它呢？</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Joanne McNeil’s début novel, “Wrong Way,” is a useful literary bellwether of this shift: a novel about the self-driving-car business that feels less like a vision of the future than a dispatch from the present. The story is told from the perspective of Teresa, a forty-eight-year-old Massachusetts woman who responds to a vague “Drivers Wanted” Craigslist ad posted by a recruiter on behalf of a Google-ish tech conglomerate called AllOver. At her orientation, she’s shown a video advertising an AllOver driverless electric taxi called the CR. But each CR, it turns out, has a human backup operator stashed inside, hidden from passengers, watching the road on a video screen. Teresa is a safety driver, of sorts, but a secret one: her passengers, she’s told, won’t know she’s there.</p>
    <p>乔安妮·麦尼尔的处女作小说《错误方向》是这一转变的文学风向标：这是一部关于自动驾驶汽车行业的小说，与其说是对未来的设想，不如说是来自当下的报告。 故事是从特蕾莎的视角讲述的，她是一位 48 岁的马萨诸塞州女性，回应了一则模糊的“招聘司机”的 Craigslist 广告，这则广告是一名招聘人员代表一家名为 AllOver 的 Google 式科技巨头发布的。 在她的入职培训中，她观看了一段宣传 AllOver 公司的无人驾驶电动出租车 CR 的视频。但事实证明，每辆 CR 中都藏有一名人类备用操作员，他们被乘客隔绝，只能在视频屏幕上观察路况。 特蕾莎也算是一名安全驾驶员，但却是秘密的：她被告知，她的乘客不会知道她的存在。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>From her perch in “the nest,” the area at the top of the CR pod where the human is hidden, Teresa drives, develops muscles aches, and watches her passengers as they zone out, argue, and take their clothes off. (Sex in San Francisco robo-taxis has become something of a tabloid preoccupation; it does appear to be happening.) She watches a passenger polishing a gun—but then, in a twist on Chekhov’s rules for such situations, updated for the age of app-alienated labor, he gets out and she never sees him again. Later, she witnesses an in-car situation that looks an awful lot like a precursor to sexual assault. She considers intervening but doesn’t, and afterward is fretfully preoccupied by how she might have handled the situation differently. Throughout, we are uneasily conscious of the fact that the CR’s software might glitch and Teresa might have to take the wheel to avert disaster. (General Motors has already pulled its Cruise robo-taxis from the streets of San Francisco after one of them drove over a woman who had already been hit by a human-controlled car, then dragged her twenty feet along the road. “Cruise is dedicated to rebuilding trust and operating at the highest standards of safety,” a company statement says.)</p>
    <p>在“鸟巢”里——那是 CR 荚舱顶部的空间，人类隐藏的地方——特蕾莎负责驾驶，同时肌肉酸痛，看着乘客们出神、争吵、脱衣服。（在旧金山的机器人出租车里做爱已经成为小报热衷的话题；这种事情确实时有发生。）她看到一名乘客正在擦拭一把枪——但随后，在这个为应用软件导致疏离的时代对契诃夫戏剧规则的一种戏仿中，那名乘客下车后，她就再也没见过他。后来，她目睹了疑似性侵前兆的情况。她考虑过介入，但没有这么做，事后她一直焦虑地琢磨自己当时本可以如何用不同的方式处理这件事。整个过程中，我们隐隐担忧 CR 的软件可能会出现故障，而特蕾莎可能不得不接管驾驶以避免灾难。（在一辆 Cruise 机器人出租车从一名已被一辆由人类驾驶的汽车撞倒的女子身上碾过，并将其拖行了二十英尺之后，通用汽车已经将其 Cruise 机器人出租车撤出了旧金山的街道。“Cruise 致力于重建信任，并按照最高的安全标准运营，”该公司的一份声明说。）</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>AllOver’s charismatic C.E.O. is a generic Silicon Valley mogul well practiced at deploying the language of social justice and altruism in the service of business; he struck me as a younger Elon Musk with better messaging discipline, and more of an interest in winning over liberals and Twitter urbanists. Like them, he uses self-driving cars as symbols that he’s innovating the world, as opposed to just wrecking it. He argues that deception of the CR is justified by the greater good. Reliable self-driving tech, he claims, is just around the corner; getting more people acclimated now means more people will use it sooner, which means it will save more lives, reduce carbon emissions and congestion, and create more mobility options for people amid the disruptions of climate change. (In another recent novel, Patrick McGinty’s “Test Drive,” the protagonist works helping to develop self-driving cars that can deal with increasingly regular and violent floods on the streets of Pittsburgh.) The conceptually simple possibility that better transit options could be provided by government, as a collective undertaking for the public good—and that this might be preferable to developing a radically new technology—is treated as an obvious non-starter.</p>
    <p>“AllOver” 魅力十足的首席执行官是一位典型的硅谷大亨，深谙运用社会正义与利他主义语言来服务于商业；给我的感觉是，他像是年轻版的埃隆·马斯克，更擅长传播话术，也更渴望赢得自由派和推特上城市规划者的好感。和他们一样，他将无人驾驶汽车当作自己是在革新世界、而非仅仅在破坏世界的象征。他认为，为了更大的利益而欺骗 CR 是正当合理的。他声称，可靠的无人驾驶技术已经近在咫尺；让更多人现在就习惯这项技术就意味着将来会有更多人使用它，这样就可以挽救更多的生命，减少碳排放和拥堵，并且在全球变暖导致的各种混乱中为人们提供更多的出行选择。（在另一部近期的小说——帕特里克·麦金蒂的《试驾》（Test Drive）中，主人公的工作就是帮助开发能够应对匹兹堡街道上越来越频繁、越来越猛烈的洪水的无人驾驶汽车。）从概念上讲，由政府作为集体努力为了公共利益而提供更好的公共交通选择的可能性很简单——并且这可能比开发一种全新技术更好——但这种可能性被视为显然不会成功的选择。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>By putting a human in each CR, McNeil suggests that much of what we’re told to think of as technological progress is really just a new way to obscure human labor. In a recent interview, she described travelling to Phoenix to see driverless Waymo taxis in action. During her visit, it was raining every day; as a result, every Waymo she booked had a human driver fully operating the car. “Unless someone was in the car, as I was,” she said, “they wouldn’t know that this car was being driven by a human—they would think it’s just a safety driver there to observe, or they might not see the driver at all.”</p>
    <p>麦克尼尔认为，在每个 CR 中都安排一个人，意味着我们被告知要认为是技术进步的许多事物实际上只是掩盖人工劳动的新方式。在最近的一次访谈中，她讲述了自己前往菲尼克斯观看无人 Waymo 出租车运营的经历。由于她访问期间每天都下雨，因此她预约的每一辆 Waymo 都是由人工司机全程驾驶的。她说：“除非有人像我一样坐在车里，否则他们不会知道这辆车是由人驾驶的——他们可能会以为安全驾驶员只是坐在那里观察，或者根本看不到驾驶员。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Lest we miss the parallel, the AllOver representative who leads Teresa’s training makes reference to the Mechanical Turk, an eighteenth-century machine that was presented to the public as a chess-playing automaton, but in reality had a chessmaster hidden inside. “Here’s a fact that I find fascinating,” the representative says. “Alexander Graham Bell invented the telephone because he believed the Turk was real. That is to say, he reverse engineered a magic trick. Belief in the Turk sparked a full century of bleeding-edge, tomorrow-building opportunity.” Some sleight of hand is O.K., the representative appears to think, as long as you’re doing it to inspire innovation. McNeil never shows us whether the representative is a duplicitous hype man or a believer in his own argument. But it’s clear that it doesn’t matter: either way, the CRs are out there, picking up customers who don’t—and can’t—quite understand what they’re buying into.</p>
    <p>为了让我们不会错过这种并行关系，负责训练泰蕾莎的“全面覆盖”公司代表提到了机械土耳其人，那是一款十八世纪的机器，它被展示给公众时被说成是一个能下国际象棋的自动装置，但实际上里面却隐藏了一位国际象棋大师。“这里有一个我觉得很迷人的事实，”这位代表说道，“亚历山大·格雷厄姆·贝尔之所以发明电话，是因为他相信机械土耳其人是真实的。也就是说，他反向破解了一个魔术。对机械土耳其人的信仰激发了一个多世纪的尖端机遇，那是建立未来世界的机遇。”这位代表似乎认为，只要是为了激励创新，那么玩一些障眼法也是可以接受的。麦克尼尔并没有向我们展现这位代表究竟是一个两面三刀的吹鼓手还是自己言论的忠实信徒。但很明显，这并不重要：无论如何，客户代表们就在那里，接待着那些无法——也不能——完全明白自己究竟买进了什么的顾客们。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>McNeil’s first book, “Lurking: How a Person Became a User,” was a loose history of the Internet grounded in the perspective of people logging on. She was, like many contemporary tech writers, keen to document and denounce all the ways that large corporations had reshaped the Web into a more unpleasant place as they relentlessly sought new ways to transform people’s online experiences into sources of revenue. And she was already complaining about the labor coördinates of the self-driving-car ecosystem, noting her suspicion that Google CAPTCHAs were conscripting her as an unpaid laborer in the company’s driverless car program. (In 2021, a Google spokesperson said it no longer uses CAPTCHAs to train A.I. algorithms.)</p>
    <p>麦尼尔的第一本书《潜行：从人到用户》大致是一部互联网史，书中从上网的人们的视角出发，讲述了互联网的发展历程。和许多当代科技作家一样，她热衷于记录大型企业为不断将人们的在线体验转化为收入来源而对网络世界造成的种种不良影响，并对此提出批评。她已经开始抱怨无人驾驶汽车生态体系中的劳动协作问题，并指出她怀疑谷歌验证码是在把她变成该公司无人驾驶项目中一名没有报酬的劳工。（2021年，一位谷歌发言人表示公司已不再使用验证码来训练人工智能算法。）</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>But, in contrast to many jeremiads on the subject, “Lurking” was, as first order of business, concerned with the motivations that brought people to the Web in the first place and also kept them there, even amid awareness of its less savory aspects. In McNeil’s eyes, the Internet is a palimpsest not just of corporate greed but also of its users’ intense and sometimes contradictory longings: for community and privacy, authenticity and escape.</p>
    <p>但与许多对该主题的悲观论调不同的是,“潜伏”首先关注的是人们最初为何会来到网络、又是什么让他们留了下来,哪怕他们已经意识到网络不那么令人愉快的一面。在麦克尼尔看来,互联网不仅是企业贪婪的体现,也是用户复杂而有时相互矛盾的需求的反映:他们渴望群体,也渴望隐私,渴望真实,也渴望逃离。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>“Wrong Way” is recognizably the work of the same author. McNeil is less interested in whether AllOver is “good” or “bad” than in why Teresa works for them either way. The answers are familiar. She needs money to rent an apartment, and she needs an apartment to have space away from her mother’s oppressive presence and think on her own. She needs money to afford her membership at the Y.M.C.A., where she gets the mind-reordering pleasure of swimming laps. One of McNeil’s quiet accomplishments is the effectiveness with which she brings these desires to life; in honoring our primal need for little pockets of comfort, she subtly draws our attention to the power that accrues to the institutions that help us get them. The book’s central image—of a person stuffed inside a hidden compartment in the car—is less subtle but surprisingly effective: it gets us thinking about tech in a way that’s refreshingly visceral, the human driver producing a “queer feeling” to rival that once produced by their absence. And it’s not terribly far off from reality. According to a recent Times story, before General Motors pulled its Cruise taxis out of San Francisco, they were being supported by a remote staff: 1.5 workers for each car, frequently intervening remotely in response to distress signals.</p>
    <p>“Wrong Way” 显然是出自同一作者之手。 麦克尼尔不太关心“AllOver”是好是坏，她更想探讨的是特蕾莎为何无论如何都会为它工作。答案都是些老生常谈：她需要钱来租公寓，而她之所以要租公寓，是为了摆脱母亲的压迫，拥有独立思考的空间。她需要钱来支付基督教青年会的会员费，在那里游泳往返几个来回就能让她的大脑焕然一新。麦克尼尔一个较为低调的成就就是她把这些欲望写得栩栩如生；她尊重我们对舒适小窝的基本需求，并巧妙地将我们的注意力引向了那些能满足这些需求的机构所拥有的力量。这本书的核心意象——一个人藏在车里的暗格中——虽然不够含蓄，但出奇地有效：它让我们以一种焕然一新的直观方式去思考科技，人类司机的存在让人产生了一种“诡异的感觉”，与曾经只有汽车没有司机时的感觉不分伯仲。这离现实也不远。根据最近的一篇《纽约时报》的报道，在通用汽车公司把它的Cruise出租车从旧金山撤出之前，它们是由远程工作人员支持的：每辆车配备1.5名员工，他们经常远程响应车辆发出的求救信号。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>With its corporate machinations, creepy secrets, and low-ranking Everywoman protagonist, the novel seems, at first, like a standard-issue techno-thriller. But, just as the CR’s futuristic façade conceals something distinctly less high-tech, “Wrong Way” reveals itself to be something with a much lower heart rate: a leisurely novel of day-in, day-out gig work in the greater Boston area. The most memorable passages aren’t about self-driving cars. Instead, they’re about Teresa’s ruminations on what makes a job a “good” one, and whether driving for AllOver counts; about awkward but sweet first hangs that might be dates; about sharing private thoughts (and possible delusions) with another human; about having parents, about having siblings; about train commutes. A surprisingly long stretch is about what it’s like to work, as Teresa did for a while, at a modern-art museum in New York. The book is, in other words, a tale of drift in the gig economy—but one you get coaxed into reading by the novelty of its conceit.</p>
    <p>这部小说里有企业种种幕后操作、阴暗秘密以及地位低微的女主角，乍一看像是俗套的技术惊悚小说。但就像“CR”那 futuristic 的外表掩盖着不够高科技的真实一面一样，《Wrong Way》最终展现出来的内容更平静：这是一本关于在大波士顿地区从事零工的悠闲小说。最令人难忘的段落并不是关于无人驾驶汽车的。相反，它们讲述的是特蕾莎对于什么样的工作才是“好”工作的思考，以及为“AllOver”开车算不算；讲述的是可能成为第一次约会的尴尬而甜蜜的初次外出；讲述的是与另一个人分享私人想法（和可能的妄想）；讲述的是拥有父母、拥有兄弟姐妹的感受；讲述的是通勤列车。有一大段内容令人意外地讲述了特蕾莎曾在纽约一家现代艺术博物馆工作过一段时间的经历。换句话说，这本书讲述的是零工经济中随波逐流的故事——但这个故事的概念很新颖，足以吸引你读下去。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Some readers, I’m sure, will find this misdirection frustrating. But it gave me a pleasant sense that I was witnessing a literary sneak attack on the very idea of “the future” as commonly constructed in fiction. “Wrong Way” is quite obviously not a sci-fi utopia, with self-driving cars helping to produce a radically better society. But it’s also not a conventional dystopia, because nothing dramatically dreadful happens. Instead, everything is wrapped in an air of mournful belatedness, the literary equivalent less of a sci-fi hellscape than of an especially gray day in Boston, the kind where it can be hard to tell what’s horribly depressing, and what’s just life. Despite the rhetoric of their hype men, McNeil seems to suggest, driverless vehicles bear no fixed relation to progress or change. Sometimes a self-driving car is just a self-driving car.</p>
    <p>我确信有些读者会觉得这种误导令人沮丧。但这也让我有种愉悦的感觉，仿佛见证了一场文学偷袭，针对的是科幻小说中常见的一种“未来”设想。“错误的方向”显然不是什么科幻乌托邦，不会有无人驾驶汽车帮助构建出一个激进的更美好社会。但它也算不上传统意义上的反乌托邦，因为并没有发生什么真正可怕的事情。相反，一切都笼罩在悲伤迟滞的氛围中，与其说这是一幅科幻地狱景象的文学写照，倒不如说是波士顿一个特别阴沉的日子，那种让人难以分辨何为真正令人沮丧、何为生活常态的日子。麦克尼尔似乎在暗示，尽管有推销者的种种说辞，无人驾驶汽车与进步或变革并没有必然联系。有时候，一辆自动驾驶汽车就是一辆自动驾驶汽车。</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>