<template>
<div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <h1>Black Holes Are Even Weirder Than You Imagined</h1>
    <h1>黑洞比你想象的还要奇怪</h1>
  </div>
  <div class='parag' :style="{gridTemplateColumns: gridTemplateColumns,  marginBottom: '24px'}">
    <h5>It’s now thought that they could illuminate fundamental questions in physics, settle questions about Einstein’s theories, and even help explain the universe.</h5>
    <h5>现在人们认为它们能够揭示物理学的基本问题， 解决关于爱因斯坦理论的谜题， 甚至帮助我们理解宇宙。</h5>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Black holes are, of course, awesome. But, for scientists, they are more awesome. If a rainbow is marvellous, then understanding how all the colors of the rainbow are present, unified, in ordinary white light—that’s more marvellous. (Though, famously, in his poem “Lamia,” John Keats disagreed, blaming “cold philosophy” for unweaving the rainbow.) In recent years, the amount of data that scientists have discovered about black holes has grown exponentially. In January, astronomers announced that the James Webb Space Telescope had observed the oldest black hole yet—one present when the universe was a mere four hundred million years old. (It’s estimated that it’s now 13.8 billion years old.) Recently, two supermassive black holes, with a combined mass of twenty-eight billion suns, were measured and shown to have been rotating tightly around each other, but not colliding, for the past three billion years. And those are just the examples that are easiest for the public to make some sense of. To me, a supermassive black hole sounds sublime; to a scientist, it can also be a test of wild hypotheses. “Astrophysics is an exercise in incredible experiments not runnable on Earth,” Avery Broderick, a theoretical physicist at the University of Waterloo and at the Perimeter Institute, told me. “And black holes are an ideal laboratory.”</p>
    <p>黑洞当然令人惊叹。但对于科学家来说，它们更加迷人。如果说彩虹美妙绝伦，那么了解彩虹中的所有颜色如何统一地存在于普通的白光中——这更是奇妙无比。（尽管约翰·济慈在其著名诗作《拉米亚》中表达了不同意见，认为“冰冷的哲学”让彩虹失去了原有的魔力。）近年来，科学家们发现的关于黑洞的数据呈指数级增长。今年1月，天文学家宣布詹姆斯·韦伯太空望远镜观测到了迄今为止最古老的黑洞——它存在于宇宙仅有四亿年的时候。（据估计，现在它的年龄为138亿年。）最近，两个合计质量为280亿个太阳的超大质量黑洞被测量到在过去30亿年间紧密旋转但没有碰撞。这些只是公众最容易理解的例子。对我来说，超大质量黑洞听起来就很震撼；对科学家来说，它们还可以用来验证一些大胆的假设。“天体物理学是在地球上无法进行的惊人实验的实践”，滑铁卢大学和圆周理论物理研究所的理论物理学家艾弗里·布罗德里克告诉我，“而黑洞是理想的实验室。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Broderick says that he studies black holes because they are very simple, theoretically and mathematically. As he explained it, a black hole has a mass, an electrical charge, and an angular momentum (meaning that it can spin). “And that’s pretty much it,” he said. “Their behavior is extreme, but the apparatus is something we think we understand.” Another “simple” way to think of a black hole is as an extraordinary amount of mass in a relatively small space. It exerts a gravitational pull so strong that not even light can escape it. Imagine the mass of Earth condensed to the volume of a marble; imagine a million suns condensed to the volume of a single sun—that’ll give you an idea of a black hole. Some black holes are formed by stars that have collapsed in on themselves. Other black holes are thought to have been formed by the inward collapse of enormous clouds of gas. (There are other theories, too.) To look “into” a black hole—from which no photon or wave or ray ever returns—requires considerable creativity. The interior of a black hole can only be deduced from changes exterior to it. Active black holes are encircled by intense brightness and billion-degree heat, given off by matter falling toward them—think of the fire of an incoming asteroid—while the black hole itself is unthinkably cold, a tiny fraction of a degree above absolute zero.</p>
    <p>布罗德里克说他之所以研究黑洞，是因为它们在理论和数学上都非常简单。正如他所解释的那样，一个黑洞具有质量、电荷和角动量（也就是说它可以旋转）。“差不多就是这些，”他说，“它们的行为极端，但构成它们的机制是我们认为自己理解的东西。”思考黑洞的另一种“简单”方式是将其视为相对较小的空间内存在极大质量。它产生的引力如此之强，以至于连光都无法逃脱。想象一下地球的质量浓缩为一颗弹珠大小；想象一下一百万个太阳的质量浓缩为一颗太阳大小——这样你就能对黑洞有所了解了。有些黑洞是由自身坍塌的恒星形成的。人们认为其他一些黑洞是由巨大的气体云向内坍塌形成的。（还有其他理论。）要“观察”黑洞——没有任何光子、波或射线能从中返回——需要极大的创造力。只能从黑洞外部的变化来推断其内部的情况。活跃的黑洞周围环绕着强烈的亮度和十亿度的高温，这是由向其坠落的物质发出的——想象一下即将撞击地球的小行星燃烧的情景——而黑洞本身却不可思议地寒冷，温度仅比绝对零度高一点点。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>It’s in these simple, outlandish objects, Broderick explained, “that twentieth-century physics breaks down.” But what is the twentieth-century physics that is said to break down? Basically, there’s Albert Einstein’s theory of general relativity (which made a tiny but far-reaching correction to Isaac Newton’s concept of gravity), and there’s quantum mechanics. “General relativity is thought of as the theory of the very large and massive, and quantum mechanics is the theory of the very small or very cold,” Broderick said. Black holes are massive (general relativity), and cold (quantum mechanics). But, when scientists attempt to use these theories to describe what happens in the interior of a black hole, the implications are, as another astrophysicist put it, “a disaster.” Or, as Broderick put it, the theories “give very different answers.”</p>
    <p>布罗德里克解释说，正是在这些简单而又异想天开的物体中，“20世纪的物理学理论陷入了困境。”但所谓陷入困境的20世纪物理学到底是什么呢？基本上就是指阿尔伯特·爱因斯坦的广义相对论（这一理论对艾萨克·牛顿的引力概念做了微小却影响深远的修正）和量子力学。“广义相对论通常被视作是描述宏大与质量的理论，而量子力学则是描述极微小或极低温状态的理论，”布罗德里克说。黑洞质量极大（适用于广义相对论），温度极低（适用于量子力学）。但是当科学家尝试运用这两种理论来描述黑洞内部发生的情况时，结果就像另一位天体物理学家所说的那样，“是一场灾难。”或者正如布罗德里克所说，两种理论“给出了截然不同的答案。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Some scientific terms have more charisma than others. Schrödinger’s cat, dark matter, the “plum pudding” model of the atom—these are more evocative than “eigenstates,” “neutron stars,” or “ribosomes.” “I had been searching for just the right term for months, mulling it over in bed, in the bathtub, in my car, wherever I had quiet moments,” the late physicist John Wheeler once said, about trying to find better language for what was then called a “gravitationally completely collapsed object.” Wheeler, who also read poetry, loved dreaming up vivid language for new concepts in physics. It is to Wheeler that we owe “wormholes,” the “participatory universe,” and “quantum foam”—names that carry something of the spirit of what they describe.</p>
    <p>有些科学术语就是比其他的更有魅力。薛定谔的猫、暗物质、“带负电粒子的原子模型”——这些听起来就比“特征态”、“中子星”或“核糖体”要引人入胜。“我花了几个月的时间苦苦思索，躺在床上想，在浴缸里想，在车上想，但凡能静下心来的时候我都在想”，已故物理学家约翰·惠勒曾这样描述自己尝试为当时被称为“引力完全坍缩天体”的事物寻找更佳表述的过程。惠勒本人也读诗，他乐于为物理学中的新概念创造出富有表现力的语言。“虫洞”、“参与性宇宙”和“量子泡沫”这些名词都归功于惠勒，它们在一定程度上传达出了所描述事物的精神特质。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>In 1967, Wheeler attended a discussion of the astrophysicist Jocelyn Bell’s recent discovery of pulsars—celestial objects that flash out radiation. The discussion centered on what caused this curious phenomenon. A “completely collapsed object” was one explanation. When Wheeler spoke, he used that cumbersome term several times before finding himself simply saying “black hole.” The name stuck. (That, anyhow, is one of the origin stories—the term had been used in articles a few years earlier, and it is also said to have been shouted out as a suggestion to Wheeler by a conference attendee.)</p>
    <p>1967 年，惠勒参加了一场关于天体物理学家乔丝琳·贝尔（Jocelyn Bell）最近发现的脉冲星的讨论会——这是一种会发射出辐射的天体。讨论的焦点在于导致这种奇异现象的原因。其中一个解释是“完全坍塌的物体”。惠勒发言时，他先是几次用到了这个拗口的术语，后来索性就说成了“黑洞”。这个名字就这样被固定了下来。（不管怎么说，这只是起源故事之一——几年前发表的文章中就已经用到了这一术语，还有一种说法是在一次会议上有人向惠勒建议了这个名字。）</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>For most people, the name evokes what the Nobel Prize-winning astrophysicist Saul Perlmutter termed “the Darth Vader aspect” of black holes: the objects are “deadly, silent, all-powerful, and looming.” The popular understanding of black holes, though not precise, has the accuracy that we associate with the poetry that Wheeler loved to read. “Not only does it swallow anything that comes too near it but no one lives to tell the tale . . . there are footprints leading in, and no footprints leading out,” Perlmutter said, describing how nonspecialists might think of them. “If black holes weren’t real, I think the science-fiction writers would have wanted to invent them.”</p>
    <p>对大多数人来说，这个名字让人联想到诺贝尔奖得主、天体物理学家索尔·珀尔马特 (Saul Perlmutter) 所说的黑洞“达斯·维达的一面”：这些天体“致命、寂静、无所不能且迫在眉睫”。虽然人们对黑洞的普遍理解并不精确，但它具有惠勒喜爱阅读的那种诗歌的准确性。“它们不仅吞噬一切过于接近的东西，而且没有人能讲述这个故事……只有走进去的脚印，没有走出去的脚印。”珀尔马特描述了非专业人士可能如何思考这个问题。“如果黑洞不是真实存在的，我想科幻小说作家们会想要发明它们的。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>A hundred years ago, almost no one believed that black holes were real, not even Einstein, who wrote the equations that predicted them. He said that they were impossible, a quirk of mathematics. In 1935, at a meeting of the Royal Astronomical Society, the young astrophysicist Subrahmanyan Chandrasekhar presented his work, which suggested, instead, that what was impossible was essentially that black holes didn’t exist. Sir Arthur Eddington, one of the most respected elders of astronomy, had arranged Chandrasekhar’s talk and knew what he was going to speak about—and he scheduled himself to speak directly afterward. Eddington, who was polite, open-minded, and encouraging to younger scientists, dismissed Chandrasekhar’s idea as ludicrous, saying, “There should be a law of nature to prevent a star from behaving in this absurd way!” Eddington’s viewpoint won; talking about stellar collapse became a great way not to be taken seriously.</p>
    <p>一百年前，几乎没有人相信黑洞是真实存在的，就连写下预言黑洞的方程的爱因斯坦也难以置信。他曾说黑洞是不可能的，不过是数学上的一个怪象。1935年，在英国皇家天文学会的一次会议上，年轻的天体物理学家苏布拉马尼扬·钱德拉塞卡发表了演讲，他的工作则暗示，真正不可能的事情实际上是黑洞不存在。天文学界最受尊敬的前辈之一阿瑟·爱丁顿爵士为钱德拉塞卡安排了这次演讲，并且事先就知道他要讲什么——但他还是把自己的演讲安排在了钱德拉塞卡之后。爱丁顿待人礼貌、思想开明，对年轻科学家也很鼓励，但他却认为钱德拉塞卡的想法荒谬至极，他说：“应该有一条自然法则能够阻止星星以如此荒唐的方式运行！”爱丁顿的观点占了上风；讨论恒星坍缩从此成了不务正业的代名词。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Decades passed. Then a few weird things were noticed. Astronomers began seeing something at the center of galaxies so bright that it outshone all the other stars in the galaxy put together. (This was the energy from things falling into a black hole.) Elsewhere, cosmic rays were detected from a part of the sky termed Cygnus X-1, in a pattern that seemed inexplicable. Ultimately, the concept of black holes came to account for and unify these baffling and seemingly disparate observations. Denying the existence of black holes became more awkward than accepting it. In the nineteen-seventies, Stephen Hawking had made a bet with Kip Thorne, a fellow-physicist, about whether the cosmic X rays coming from Cygnus X-1 could really be the result of a black hole. Hawking bet No, though he made the wager to counterbalance the outcome that he wanted to be true; he had spent years studying black holes. Only in 1990 had enough evidence accumulated to settle the bet in Thorne’s favor. (The payout was a subscription to Penthouse; if Hawking had won, he would have received the satirical magazine Private Eye.)</p>
    <p>几十年过去了，人们开始注意到一些奇怪的现象。天文学家们开始发现星系的中心存在某种极为明亮的物质，其光芒甚至盖过了整个星系中的所有恒星（这正是物质落入黑洞时所释放的能量）。在宇宙的另一个角落，天文学家们从天鹅座X-1探测到了宇宙射线，其模式似乎无法解释。最终，“黑洞”这一概念被用来解释和统一这些令人费解、看似无关的观测结果。否认黑洞的存在比承认它更让人尴尬。20世纪70年代，史蒂芬·霍金与物理学家基普·索恩就天鹅座X-1发出的宇宙X射线是否真的来自黑洞打了个赌。霍金押了“不是”，尽管他打赌是为了平衡自己希望的结果；毕竟他花了多年时间研究黑洞。直到1990年，才积累了足够的证据判定索恩获胜。（赌注是《花花公子》杂志的订阅；如果霍金赢了，他将收到讽刺杂志《私眼》。）</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>From there, knowledge accelerated. Not only were black holes real but a giant one was at the center of our galaxy—actually, at the center of every galaxy—actually, not only at the center of galaxies but all over them, with our Milky Way alone housing many millions. And not only are there unthinkable numbers of black holes but sometimes they collide, sending tiny ripples of gravitational waves across the universe. In 2015, scientists at LIGO, an observatory whose construction had taken decades of dreaming and designing and revising, ran an experiment that within days detected those gravitational waves. The researchers described what they observed, evocatively, as ripples in the fabric of space-time.</p>
    <p>从那以后，人类对黑洞的认识飞速发展。不但证实了黑洞是真实存在的，而且发现有一个巨大的黑洞位于我们银河系的中心——实际上，在每一个星系的中心都有一个巨大的黑洞——实际上，不仅在星系的中心存在黑洞，整个星系中到处都是黑洞，仅我们所在的银河系就有数以百万计的黑洞。宇宙中黑洞的数量之多，令人难以想象，而有时这些黑洞会相撞，从而在整个宇宙中引发微小的引力波涟漪。2015年，位于LIGO的科学家们开展了一项实验，在短短几天内就探测到了引力波，LIGO是一个集数十年的梦想、设计与改进为一体的天文台。研究人员将他们观测到的现象生动地描述为时空结构中的涟漪。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The gravitational waves sent out by colliding black holes make a sound—or translate into a sound—something like a bell being rung. “You can tell if I’m pounding on this desk, or if I’m pounding on the floor,” Will Farr, an astrophysicist, said to me in his bright office at the Flatiron Institute, in Manhattan. “If I had musical instruments, it would sound prettier, but also you could tell if it was a trumpet or a trombone or drums or a clarinet—even when they’re making the same note.”</p>
    <p>由碰撞的黑洞发出的引力波会产生一种声音——或者说能转化成一种声音——就像在敲响一口钟。“你能分辨出我是敲打这张桌子还是敲打地板，”天体物理学家威尔·法尔在位于曼哈顿的菲特里诺研究所光线明亮的办公室里对我说。“如果我有乐器的话，那听起来会更悦耳一些，但即便如此你也能分辨出这是小号、长号、鼓还是竖笛——哪怕它们演奏的是同一个音符。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>The sound made when you strike an object—or pull a bow across it, or blow air into a reed connected to it—carries information about the object’s shape, material makeup, and temperature. “You can identify an instrument by listening to what we call the spectrum—the different frequencies of the modes that are excited when you hit it,” Farr said. Black holes have modes, too, though they radiate in gravitational waves, not sound waves. So if you, say, pounded on a black hole, in theory, you could tell quite a bit about it. Two black holes colliding in effect do that pounding which scientists cannot themselves do—an experiment out in the cosmos.</p>
    <p>当你敲击一个物体时（或者在它上面拉弓，或者对着连接它的簧片吹气），所产生的声音携带着有关该物体形状、材质乃至温度的信息。“你可以通过我们所说的频谱——也就是你敲击时激发的不同频率的模式来识别一件乐器，”法尔说。黑洞也有不同的模式，不过它们释放出的是引力波而非声波。因此，从理论上讲，如果你敲击一个黑洞，就能了解许多有关它的信息。两个黑洞相撞实际上就起到了这样的敲击作用——这是科学家自己无法做到的实验：一场在宇宙中进行的实验。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Farr described the moment of collision between two holes as forming a shape like a “black peanut,” which eventually settles into a single, merged black hole. “Ringdown” is the term used to describe both that final merging and the “sound”—the waves—emitted by it. The ripples from a ringdown, if recorded precisely enough, could tell the story of a black hole: its spin, its mass, and its charge, and possibly information about the million-degree hot-gas ring external to it. “Basically, there’s currently no other way to probe this region of space-time except with gravitational waves,” Farr said. Light waves, radio waves, X rays—none of these ways of reading the universe let scientists see as far down toward the horizon of a black hole. “That’s one reason why it’s been revolutionary to have this tool.”</p>
    <p>法尔描述了两个黑洞碰撞时形成的形状就像一颗“黑色的花生”，最终会变成一个合并后的单一黑洞。“并合震荡”是用来描述最后的融合过程以及由此产生的“声音”——也就是它发出的引力波。如果能足够精确地记录下这些并合震荡所产生的涟漪，就能讲述有关黑洞的故事：它的自转、质量、电荷，甚至可能还有关于其外部百万度热气体环的信息。“基本上，目前除了通过引力波之外，没有其他方法可以探测这一时空区域。”法尔说。光波、无线电波、X射线——所有这些解读宇宙的方式都无法让科学家看到接近黑洞视界的景象。“这就是为什么拥有这一工具会带来一场革命的原因之一。”</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Ringdown may be used by researchers to test if general relativity accurately describes black holes. If it does, then the ringdown tones will come out one way; if not, then they won’t. “By examining the deviations in detail, tone by tone, you can try to understand where the deviation from general relativity is coming,” Farr said.</p>
    <p>研究人员可以利用“尾声”来验证广义相对论对于黑洞的描述是否准确。如果答案是肯定的，“尾声”的音调就会以某种形式出现；反之则不会。“通过详细检查每一次偏离、每一个音调，你可以尝试理解与广义相对论相悖的现象来自何处，”法尔说道。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>It will be a while before the public has a “feel” for gravitational waves, or for how black holes do or don’t unify quantum mechanics and general relativity. But those ideas still filter into the public imagination, however fuzzily. In 2020, the astrophysicist Andrea Ghez, of the University of California, Los Angeles, and a colleague received a Nobel for having tracked the path of objects near the center of our galaxy in sufficient detail to indicate that there must be a supermassive black hole there. In 2014, through an ingenious and sparsely funded passion project conducted by hundreds of scientists, the Event Horizon Telescope (E.H.T.) was assembled, with the goal of “photographing” a black hole. The E.H.T. is not one telescope but a network of initially eight and now eleven, spread across the planet. Together, the telescopes function as if they were one telescope with a lens the size of Earth. The E.H.T. gathered data on a distant black hole and then on a nearer one at the heart of the Milky Way. Images came through of the two black holes—or, rather, of the ring of stuff falling into the black holes.</p>
    <p>公众要想对引力波有所“感觉”，或是理解黑洞如何与量子力学和广义相对论相统一（如果确实存在这种统一的话），还需要一段时间。但这些观念仍然会以一种模糊的方式进入公众的想象中。2020年，加州大学洛杉矶分校的天体物理学家安德烈娅·盖兹和一位同事因详细追踪了银河系中心附近物体的运动轨迹，证明那里必定存在一个超大质量黑洞，而获得了诺贝尔奖。2014年，在数百名科学家通过一项既巧妙又资金不足的充满激情的研究项目中，事件视界望远镜（E.H.T.）组装完成，其目标是“拍摄”一张黑洞的照片。事件视界望远镜不是一个单独的望远镜，而是一个由最初八个、现在十一个分布在全球各地的望远镜组成的网络。这些望远镜共同工作时，就像一个有着地球大小透镜的单一望远镜。事件视界望远镜收集了一个遥远黑洞的数据，然后又收集了位于银河系中心的一个较近黑洞的数据。两张黑洞——或者更确切地说，是正在落入黑洞中的物质环——的照片出现了。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>To share the work with the general public, the scientists translated the data into astonishing images that were published all around the world. Because what the telescopes “saw” is at wavelengths outside the spectrum visible to the human eye, E.H.T. scientists made decisions about, for example, what color to use to depict the extreme heat of the plasma around the event horizon. (Even though blue flames are hotter than orange-red ones, they chose an orange-red color.) A number of scientists I spoke with about the images were gently indifferent, saying that they didn’t add to their fundamental understanding of black holes. Most were more impressed with the creative means of collecting the data than with the images themselves. (In contrast, for a certain crowd, the waveform that appeared when LIGO detected gravitational waves is a popular tattoo.) For other earthlings, that darkness, surrounded by its burning ring of fire, had the intimate quality of a Polaroid—but one of the alien that we call our universe.</p>
    <p>为了向公众展示这项工作，科学家们将数据转化成了震撼的图像，并在全世界范围内发表。由于这些望远镜所“看到”的波段超出了人眼可见范围，E.H.T. 的科学家们需要做出一些决定，比如使用什么颜色来描绘事件视界周围等离子体的极端高温（尽管蓝色火焰比橙红色火焰温度更高，但他们还是选择了橙红色）。我向几位科学家展示了这些图像，他们对此态度温和但不以为意，认为这些图像并没有增加他们对黑洞的基本理解。大多数人对收集数据的创造性方式的印象要比对图像本身深刻。（与此相反的是，对某些人而言，LIGO 探测到引力波时出现的波形图是一处热门的纹身图案。）对于其他地球居民来说，那片被火焰光环环绕的黑暗具有宝丽来快照般的亲切感——不过它的拍摄对象是我们称之为宇宙的未知世界。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>Broderick, who was one of the first theoretical physicists to join the E.H.T., told me that, for scientists, the adage “seeing is believing” doesn’t always hold true; scientists often have to decide if they can trust what they see. He framed the E.H.T. as contributing both societal impact and scientific impact. It was “pleasingly novel to work on something I can tell my in-laws and mother about,” he said. He pointed out that it was estimated that half the world’s population had seen the first black-hole image: “I’m actually kind of curious; when was the last time so many newspapers had the same thing on their front page? We all shared this experience together, and there are precious few such things, and most of them are negative.” He saw the E.H.T. as a chance to make part of the story of physics real and visible.</p>
    <p>最早参与E.H.T.的理论物理学家之一布罗德里克告诉我，对科学家而言，“眼见为实”这句老话并不总是适用；他们常常必须判断自己所见是否可信。他认为E.H.T.兼具社会影响力与科学影响力。他说：“能从事一件我可以向岳父母和母亲解释的事物，令人感到新奇有趣。”他还提到，据估计全球有一半人口都看到了首张黑洞照片：“我其实很好奇，上一次这么多报纸头版出现同一则新闻是什么时候？我们共同经历了这一刻，这样的经验并不多见，而且多数是负面事件。”他认为E.H.T.让物理学的部分故事得以具体呈现在世人眼前。</p>
  </div>
  <div class='parag' :style="{ gridTemplateColumns: gridTemplateColumns }">
    <p>As a kid, Broderick watched “Star Trek,” “Doctor Who,” and “anything adventurous,” he said, with his father, whom he would visit in the summer and on holidays. “He would record these movies and shows in anticipation of me coming, so we would binge-watch before it was a thing,” he said. His father was quadriplegic, and enjoyed photography and movies. Broderick told me that his viewing of “Star Trek” is not unrelated to his work as a theoretical physicist. In every episode, he said, the Starfleet travelled to incredible new places, and saw something different, and that was the adventure. “A part of what drew me to astrophysics was that Starfleet doesn’t exist. But I get to travel the universe with telescopes, large computers, blackboards, whiteboards, chalk—with whatever.”</p>
    <p>布罗德里克小时候看过《星际迷航》、《神秘博士》以及“任何冒险类的”电视剧，他告诉我，这些剧都是和父亲一起看的，他只有夏天和假期的时候才能见到父亲。他说：“父亲会提前录下这些电影和电视剧集等着我来，所以我们其实很早就开始‘追剧’了。”他的父亲是四肢瘫痪患者，喜欢摄影和电影。布罗德里克对我说，自己之所以会观看《星际迷航》，跟他后来成为理论物理学家不无关系。他说每一集中，星际舰队都会前往奇妙的新世界，看到不一样的东西，这就是冒险。“吸引我投身天体物理学的部分原因就是现实中并没有星际舰队。但借助望远镜、大型计算机、黑板、白板和粉笔等工具，我可以遨游宇宙。”</p>
  </div>
</div>
</template>
<script>export default {  props: {    gridTemplateColumns: {      type: String,      required: true,    },  },};</script>